<?php
/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function summergame_help($path, $arg) {
  $content = '';
  switch ($path) {
    case "admin/help#summergame":
      $content = '<p>'. t('Summer Game system') .'</p>';
      break;
  }
  return $content;
}

/**
 * Implementation of hook_init()
 * Turns off caching for all summergame pages
 */
function summergame_init() {
  if (strpos($_GET['q'], 'summergame') === 0) {
    $GLOBALS['conf']['cache'] = FALSE;
  }

  global $user;
  if ($user->uid) {
    // Get all players for this user
    $user_players = summergame_player_load_all($user->uid);
    // Determine currently active player
    if ($user->sg_active_pid) {
      foreach ($user_players as $i => $user_player) {
        if ($user_player['pid'] == $user->sg_active_pid) {
          $active_player = $user_player;
          unset($user_players[$i]);
        }
      }
    }
    else {
      $active_player = array_shift($user_players);
    }

    $user->player = summergame_player_load($active_player['pid']);
    $user->other_players = $user_players;
  }
}

/**
 * Implementation of hook_user()
 */
function summergame_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'view') {
    if ($players = summergame_player_load_all($account->uid)) {
      $account->content['summergame'] = array(
        '#type' => 'user_profile_category',
        '#title' => t('Summer Game Player') . (count($players) == 1 ? '' : 's'),
        '#weight' => 0,
      );
      foreach ($players as $player) {
        $player_text = ($player['nickname'] ? $player['name'] . ' (' . $player['nickname'] . ')' : $player['name']);
        $account->content['summergame']['player' . $player['pid']] = array(
          '#type' => 'user_profile_item',
          '#value' => l($player_text, 'summergame/player/' . $player['pid']),
        );
      }
    }
  }
}

/**
 * Implementation of hook_menu().
 */
/*
function summergame_menu() {
  $items = array();

  $items['admin/settings/summergame'] = array(
    'title' => 'Summer Game Settings',
    'description' => 'Site Settings for the Summer Game',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summergame_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['summergame/admin'] = array(
    'title' => 'Summer Game Admin',
    'description' => 'Administer the Summer Game',
    'page callback' => 'summergame_admin',
    'access arguments' => array('manage summergame'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['summergame/admin/gamecodes'] = array(
    'title' => 'Administer Game Codes',
    'page callback' => 'summergame_admin_gamecodes',
    'access arguments' => array('manage summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/badges'] = array(
    'title' => 'Administer Badges',
    'page callback' => 'summergame_admin_badges',
    'access arguments' => array('manage summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/add'] = array(
    'title' => 'Add new Summer Game Code',
    'page callback' => 'summergame_admin_edit',
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/edit'] = array(
    'title' => 'Edit Summer Game Code',
    'page callback' => 'summergame_admin_edit',
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/delete'] = array(
    'title' => 'Delete Summer Game code',
    'page callback' => 'summergame_admin_delete',
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/badge'] = array(
    'title' => 'Edit Summer Game Badge',
    'description' => 'Edit a Badge for the Summer Game',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summergame_admin_badge_form'),
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/players'] = array(
    'title' => 'Administer Players',
    'page callback' => 'summergame_admin_players',
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/players/merge'] = array(
    'title' => 'Administer Players',
    'page callback' => 'summergame_admin_players_merge',
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/intervention'] = array(
    'title' => t('Geekly Intervention'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summergame_intervention_form'),
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/badgeify'] = array(
    'title' => t('Player Badgeifier'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summergame_badgeifier_form'),
    'access arguments' => array('administer summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player'] = array(
    'title' => 'Summer Game Player Page',
    'page callback' => 'summergame_player_page',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/gamecode'] = array(
    'title' => 'Redeem a Summer Game Code',
    'page callback' => 'summergame_player_redeem_page',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/friends'] = array(
    'title' => 'Summer Game Player Friend Page',
    'page callback' => 'summergame_player_friend_page',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/consume'] = array(
    'title' => 'I Read/Listened/Watched Something',
    'page callback' => 'summergame_player_consume_page',
    'access callback' => 'summergame_player_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/edit'] = array(
    'title' => t('Summer Game Player Information'),
    'page callback' => 'summergame_player_edit_page',
    'access callback' => 'summergame_player_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/%/setactive'] = array(
    'title' => t('Set Active Player'),
    'page callback' => 'summergame_player_set_active',
    'page arguments' => array(2),
    'access callback' => 'summergame_player_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/gcpc'] = array(
    'title' => t('Summer Game Player Generate Cell Phone Code'),
    'page callback' => 'summergame_player_gcpc',
    'access callback' => 'summergame_player_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/gfc'] = array(
    'title' => t('Summer Game Player Generate Friend Code'),
    'page callback' => 'summergame_player_gfc',
    'access callback' => 'summergame_player_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/ledger'] = array(
    'title' => 'Summer Game Player Ledger Page',
    'page callback' => 'summergame_player_ledger_page',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/deletescore'] = array(
    'title' => t('Delete Player Score'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summergame_delete_score_form'),
    'access callback' => 'summergame_player_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/player/delete'] = array(
    'title' => t('Delete Player'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summergame_delete_player_form'),
    'access callback' => 'summergame_player_access',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/leaderboard'] = array(
    'title' => 'Game Leaderboard',
    'page callback' => 'summergame_leaderboard_page',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/badge'] = array(
    'title' => 'Summer Game Badge Detail',
    'page callback' => 'summergame_badge_detail_page',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/pdf'] = array(
    'title' => t('Summer Game PDF'),
    'page callback' => 'summergame_pdf',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
  );
  $items['summergame/admin/trivia'] = array(
    'title' => t('Trivia Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('summergame_trivia_settings'),
    'access arguments' => array('administer summergame'),
    'description' => 'Settings for the Summer Game Trivia game',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'summergame.trivia.inc',
  );
  $items['summergame/trivia'] = array(
    'title' => t('Summergame Trivia'),
    'page callback' => 'summergame_trivia_page',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
    'file' => 'summergame.trivia.inc',
  );
  $items['summergame/triviaupdate'] = array(
    'page callback' => 'summergame_trivia_update',
    'access arguments' => array('access summergame'),
    'type' => MENU_CALLBACK,
    'file' => 'summergame.trivia.inc',
  );
  return $items;
}
*/

function summergame_theme() {
  return [
    'summergame_admin_page' => [
      'variables' => [
        'print_page_url' => NULL,
        'sg_admin' => NULL,
        'gc_rows' => NULL,
        'badge_rows' => NULL,
        'limit' => NULL,
      ],
    ],
    'summergame_player_page' => [
      'variables' => [
        'summergame_points_enabled' => NULL,
        'playername' => NULL,
        'player' => NULL,
        'player_access' => NULL,
        'other_players' => NULL,
        'points' => NULL,
        'completed_classic' => NULL,
        'website_user' => NULL,
      ],
    ],
    'summergame_player_ledger' => [
      'variables' => [
        'ledger' => NULL,
        'pager' => NULL
      ]
    ],
  ];
}

function summergame_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Leaderboard Filter Block'),
      'visibility' => 1,
      'pages' => "summergame/leaderboard\nsummergame/leaderboard/*",
    );
    return $blocks;
  }
  else if ($op == 'view') {
    if ($delta == 0) {
      $block = array(
        'subject' => t('Filter Leaderboard'),
        'content' => summergame_leaderboard_filter_block_content(),
      );
    }
    return $block;
  }
}

function summergame_leaderboard_filter_block_content() {
  $current = array();
  if ($_GET['type']) {
    $current['type'] = $_GET['type'];
  }
  if ($_GET['range']) {
    $current['range'] = $_GET['range'];
  }
  if ($_GET['staff']) {
    $current['staff'] = $_GET['staff'];
  }

  // Game Types
  $content .= '<h3>Scores by Game</h3><ul>';
  $query = $current;
  unset($query['type']);
//  $content .= '<li>' . ($current['type'] ? l('All Games', 'summergame/leaderboard', array('query' => $query)) : 'All Games') . '</li>';
  $terms = summergame_get_game_terms();
  foreach ($terms as $term) {
    if ($current['type'] == $term) {
      $line_item = $term;
    }
    else {
      $query['type'] = $term;
      $line_item = l($term, 'summergame/leaderboard', array('query' => $query));
    }
    $content .= "<li>$line_item</li>";
  }
  $content .= '</ul>';

  // Time Ranges
  $content .= '<h3>Scores by Time</h3><ul>';
  $query = $current;
  unset($query['range']);
  $time_ranges = array('All Time' => '', 'This Week' => 'week', 'Today' => 'day');
  foreach ($time_ranges as $text => $code) {
    if ($current['range'] == $code) {
      $line_item = $text;
    }
    else {
      $query['range'] = $code;
      $line_item = l($text, 'summergame/leaderboard', array('query' => $query));
    }
    $content .= "<li>$line_item</li>";
  }
  $content .= '</ul>';

  // Player Groups
  $content .= '<h3>Player Groups</h3><ul>';
  $query = $current;
  if ($current['staff']) {
    unset($query['staff']);
    $content .= '<li>' . l('Public', 'summergame/leaderboard', array('query' => $query)) . '</li>';
    $content .= '<li>Staff</li>';
  }
  else {
    $query['staff'] = 1;
    $content .= '<li>Public</li>';
    $content .= '<li>' . l('Staff', 'summergame/leaderboard', array('query' => $query)) . '</li>';
  }
  $content .= '</ul>';

  return $content;
}

/**
 * PAGE: Summer Game Site Settings
 */
 /*
function summergame_settings() {
  $form['summergame_points_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Summergame Points Enabled'),
    '#default_value' => variable_get('summergame_points_enabled', 0),
    '#description' => t('Allow players to earn points?'),
  );
  $form['summergame_lego_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Summergame Lego Contest Voting Enabled'),
    '#default_value' => variable_get('summergame_lego_enabled', 0),
    '#description' => t('Turn on voting for the Lego Contest?'),
  );
  $form['summergame_dod_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Summergame Do Or Diag Enabled'),
    '#default_value' => variable_get('summergame_dod_enabled', 0),
    '#description' => t('Turn on the special Do or Diag game?'),
  );
  $form['summergame_current_game_term'] = array(
    '#type' => 'textfield',
    '#title' => t("Current Default Game Term"),
    '#default_value' => variable_get('summergame_current_game_term', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t("Default Game Term to apply to earned points (e.g. SummerGame2011)"),
  );
  $form['summergame_gamecode_default_end'] = array(
    '#type' => 'textfield',
    '#title' => t("Default Game Code End"),
    '#default_value' => variable_get('summergame_gamecode_default_end', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Default Date/Time for when a code stops being active (e.g. "2013-08-31 12:00 AM")'),
  );
  $form['summergame_completion_gamecode'] = array(
    '#type' => 'textfield',
    '#title' => t("Completion Game Code"),
    '#default_value' => variable_get('summergame_completion_gamecode', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t("Game Code awarded for completion of the Classic Reading Game (e.g. PUPPYLOVE13)"),
  );
  $form['summergame_user_search_path'] = array(
    '#type' => 'textfield',
    '#title' => t("User Search Path"),
    '#default_value' => variable_get('summergame_user_search_path', 'search/user'),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t("Path to your user search form"),
  );
  $form['summergame_print_page'] = array(
    '#type' => 'textfield',
    '#title' => t("Print Page"),
    '#default_value' => variable_get('summergame_print_page', ''),
    '#size' => 64,
    '#maxlength' => 128,
    '#description' => t("Path to the page to print summergame game cards"),
  );
  $form['summergame_catalog_domain'] = array(
    '#type' => 'textfield',
    '#title' => t("Catalog Domain"),
    '#default_value' => variable_get('summergame_catalog_domain', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t("Links to catalog pages will be directed to this domain. Leave blank for same domain. (No http:// or trailing slash)"),
  );
  $form['summergame_libphp_path'] = array(
    '#type' => 'textfield',
    '#title' => t("LibPHP path"),
    '#default_value' => variable_get('summergame_libphp_path', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Path to PHP libraries. Needs "contrib/fpdf", "contrib/fpdi", and "contrib/redisent" directories'),
  );
  $user_roles = user_roles(TRUE);
  $user_roles[0] = "NONE";
  $form['summergame_staff_role_id'] = array(
    '#type' => 'select',
    '#title' => 'Staff Role',
    '#options' => $user_roles,
    '#default_value' => variable_get('summergame_staff_role_id', ''),
    '#description' => t('Select the role that separates staff from regular players on the leaderboard'),
  );
  $form['summergame_tagger_uid'] = array(
    '#type' => 'textfield',
    '#title' => t("Tagger User ID"),
    '#default_value' => variable_get('summergame_tagger_uid', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t("User ID to own automatically created Game Code tags in the catalog"),
  );

  return system_settings_form($form);
}
*/

/**
 * PAGE: Summer Game Admin overview
 */
/*
function summergame_admin() {
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $sg_admin = user_access('administer summergame');
  $admin_users = user_access('administer users');
  $content .= '<div id="summergame-admin-page">';
  $content .= '<h1>Summer Game Admin Page</h1>';

  // Print game cards
  $print_page_url = variable_get('summergame_print_page', '');
  $content .= '<div class="print-game-cards">';
  $content .= '<h2 class="title">Print Game Cards</h2>';
  $content .= '<ul>';
  $content .= '<li class="button green">' . l("Batch Print Game Cards", $print_page_url) . '</li>';
  $content .= '</ul>';
  $content .= '</div>';

  // Players
  if ($sg_admin) {
    $content .= '<div class="admin-page-player-search">';
    $content .= '<h2 class="title">Players</h2>';
    $content .= drupal_get_form('summergame_player_search_form');
    $content .= '</div>';
  }

  // Game Codes
  if ($sg_admin) {
    $content .= '<ul class="create-new-code"><li class="button green">' . l("Create New Game Code", 'summergame/admin/add') . '</li></ul>';
  }
  $content .= '<h2 class="title game-codes">Game Codes</h2>';
  $content .= drupal_get_form('summergame_admin_gamecode_search_form');

  $limit = 25;
  $rows = array();
  $creators = array();
  $res = db_query("SELECT * FROM sg_game_codes ORDER BY created DESC LIMIT $limit");
  while ($game_code = db_fetch_array($res)) {
    // Load creator info
    $creator_uid = $game_code['creator_uid'];
    if (!$creators[$creator_uid]) {
      $creators[$creator_uid] = user_load($creator_uid);
    }
    $creator = $creators[$creator_uid];

    if (!$sg_admin) {
      $game_code['text'] = preg_replace('/\B\w/', '*', $game_code['text']);
    }

    $valid_start = $game_code['valid_start'] ? date('n/d/Y H:i:s', $game_code['valid_start']) : 'Now';
    $valid_end = date('n/d/Y H:i:s', $game_code['valid_end']);
    $rows[] = array(
      'Text' => strlen($game_code['text']) > 25 ? substr($game_code['text'], 0, 25) . '...' : $game_code['text'],
      'Description' => $game_code['description'],
      'Hint' => $game_code['hint'],
      'Points' => $game_code['points'] . ($game_code['diminishing'] ? ' (diminishing)' : ''),
      'Created' => date('n/d/Y', $game_code['created']),
      'Created By' => ($admin_users ? l($creator->name, 'user/' . $creator->uid) : $creator->name),
      'Valid Dates' => $valid_start . '-<br />' . $valid_end,
      'Game Term' => $game_code['game_term'],
      'Redemptions' => $game_code['num_redemptions'] . ' of ' . $game_code['max_redemptions'],
      'Print Sign' => l('print', 'summergame/pdf/gamecode/' . $game_code['code_id']),
      'Edit' => l('edit', 'summergame/admin/edit/' . $game_code['code_id']),
    );
  }
  $content .= theme('table', array_keys($rows[0]), $rows);
  $more_link = l('See all Game Codes', 'summergame/admin/gamecodes');
  $content .= "<p class=\"more\">Showing latest $limit game codes, $more_link</p>";

  // Badges
  if ($sg_admin) {
    $content .= '<ul class="create-new-code"><li class="button green">' . l("Create New Badge", 'summergame/admin/badge') . '</li></ul>';
  }
  $content .= '<h2 class="title">Badges</h2>';
  $sg_image_path = base_path() . file_directory_path() . '/sg_images/';
  $rows = array();
  $res = db_query("SELECT * FROM sg_badges ORDER BY bid DESC LIMIT $limit");
  while ($badge = db_fetch_array($res)) {
    if (!$sg_admin) {
      $badge['formula'] = preg_replace('/\B\w/', '*', $badge['formula']);
    }
    $rows[] = array(
      'Badge ID' => ($sg_admin ? l($badge['bid'], 'summergame/admin/badge/' . $badge['bid']) : $badge['bid']),
      'Image' => '<img src="' . $sg_image_path . $badge['image'] . '_100.png">',
      'Title' => '<strong>' . $badge['title'] . '</strong>',
      'Level' => $badge['level'],
      'Description' => $badge['description'],
      'Formula' => strlen($badge['formula']) > 25 ? substr($badge['formula'], 0, 25) . '...' : $badge['formula'],
    );
  }
  $content .= theme('table', array_keys($rows[0]), $rows);
  $more_link = l('See all Badges', 'summergame/admin/badges');
  $content .= "<p class=\"more\">Showing latest $limit badges, $more_link</p>";

  $content .= '</div>'; // #summergame-admin-page

  return $content;
}
*/

/**
 * PAGE: Show all game codes
 */
/*
function summergame_admin_gamecodes($search_term = '') {
  $admin_users = user_access('administer users');
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $content .= '<div id="summergame-admin-page">';

  // Game Codes
  $content .= '<ul class="create-new-code"><li class="button green">' . l("Create New Game Code", 'summergame/admin/add') . '</li></ul>';
  $content .= '<h2 class="title game-codes">Game Codes</h2>';
  $content .= drupal_get_form('summergame_admin_gamecode_search_form', $search_term);

  $rows = array();
  $creators = array();
  if ($search_term) {
    $res = db_query("SELECT * FROM sg_game_codes " .
                    "WHERE text LIKE '%%%s%%' " .
                    "OR description LIKE '%%%s%%' " .
                    "OR hint LIKE '%%%s%%' " .
                    "OR game_term LIKE '%%%s%%' " .
                    "OR game_term_override LIKE '%%%s%%' " .
                    "ORDER BY created DESC",
                    $search_term, $search_term, $search_term, $search_term, $search_term);
  }
  else {
    $res = db_query("SELECT * FROM sg_game_codes ORDER BY created DESC");
  }
  while ($game_code = db_fetch_array($res)) {
    // Load creator info
    $creator_uid = $game_code['creator_uid'];
    if (!$creators[$creator_uid]) {
      $creators[$creator_uid] = user_load($creator_uid);
    }
    $creator = $creators[$creator_uid];

    $game_code['text'] = (strlen($game_code['text']) > 25 ? substr($game_code['text'], 0, 25) . '...' : $game_code['text']);
    $valid_start = $game_code['valid_start'] ? date('n/d/Y H:i:s', $game_code['valid_start']) : 'Now';
    $valid_end = date('n/d/Y H:i:s', $game_code['valid_end']);
    $rows[] = array(
      'Text' => user_access('administer summergame') ? $game_code['text'] : preg_replace('/\B\w/', '*', $game_code['text']),
      'Description' => $game_code['description'],
      'Hint' => $game_code['hint'],
      'Points' => $game_code['points'] . ($game_code['diminishing'] ? ' (diminishing)' : ''),
      'Created' => date('n/d/Y', $game_code['created']),
      'Created By' => ($admin_users ? l($creator->name, 'user/' . $creator->uid) : $creator->name),
      'Valid Dates' => $valid_start . '-<br />' . $valid_end,
      'Game Term' => $game_code['game_term'],
      'Redemptions' => $game_code['num_redemptions'] . ' of ' . $game_code['max_redemptions'],
      'Print Sign' => l('print', 'summergame/pdf/gamecode/' . $game_code['code_id']),
      'Edit' => l('edit', 'summergame/admin/edit/' . $game_code['code_id']),
    );
  }
  if (count($rows)) {
    $content .= theme('table', array_keys($rows[0]), $rows);
  }
  else {
    $content .= '<p>Sorry, no gamecodes to display.</p>';
  }

  $content .= '</div>';

  return $content;
}
*/

/**
 * PAGE: Show all badges
 */
/*
function summergame_admin_badges($search_term = '') {
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $sg_admin = user_access('administer summergame');
  $admin_users = user_access('administer users');
  $content .= '<div id="summergame-admin-page">';
  $content .= '<h1>Summer Game Badges</h1>';

  // Badges
  if ($sg_admin) {
    $content .= '<ul class="create-new-code"><li class="button green">' . l("Create New Badge", 'summergame/admin/badge') . '</li></ul>';
  }
  $content .= '<h2 class="title">Badges</h2>';
  $sg_image_path = base_path() . file_directory_path() . '/sg_images/';
  $rows = array();
  $res = db_query("SELECT * FROM sg_badges ORDER BY bid DESC");
  while ($badge = db_fetch_array($res)) {
    if (!$sg_admin) {
      $badge['formula'] = preg_replace('/\B\w/', '*', $badge['formula']);
    }
    $rows[] = array(
      'Badge ID' => ($sg_admin ? l($badge['bid'], 'summergame/admin/badge/' . $badge['bid']) : $badge['bid']),
      'Image' => '<img src="' . $sg_image_path . $badge['image'] . '_100.png">',
      'Title' => '<strong>' . $badge['title'] . '</strong>',
      'Level' => $badge['level'],
      'Description' => $badge['description'],
      'Formula' => strlen($badge['formula']) > 25 ? substr($badge['formula'], 0, 25) . '...' : $badge['formula'],
    );
  }
  $content .= theme('table', array_keys($rows[0]), $rows);

  $content .= '</div>'; // #summergame-admin-page

  return $content;
}
*/

function summergame_admin_gamecode_search_form(&$form_state, $search_query = NULL) {
  $form['inline'] = array(
    '#prefix' => '<div class="container-inline">',
    '#suffix' => '</div>',
  );
  $form['inline']['search_query'] = array(
    '#type' => 'textfield',
    '#title' => 'Search Game Codes',
    '#default_value' => $search_query,
    '#size' => 25,
    '#maxlength' => 255,
  );
  $form['inline']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  if ($search_query) {
    $form['inline']['reset'] = array(
      '#type' => 'submit',
      '#value' => t('Reset to Full List'),
      '#submit' => array('summergame_admin_gamecode_search_reset'),
    );
  }
  return $form;
}

function summergame_admin_gamecode_search_form_submit($form, &$form_state) {
  drupal_goto('summergame/admin/gamecodes/' . $form_state['values']['search_query']);
}

function summergame_admin_gamecode_search_reset($form, &$form_state) {
  drupal_goto('summergame/admin/gamecodes');
}

/**
 * PAGE: Edit a game code
 */
function summergame_admin_edit($code_id = 0) {
  drupal_add_js(drupal_get_path('module', 'summergame') . '/summergame.staff.forms.js');
  if ($code_id) {
    $game_code = db_fetch_array(db_query("SELECT * FROM sg_game_codes WHERE code_id = %d", $code_id));
  }
  $content .= drupal_get_form('summergame_code_edit_form', $game_code);

  return $content;
}

/**
 * FORM: Edit a game code
 */
function summergame_code_edit_form($form_state, $game_code) {
  $form = array();
  if ($game_code['code_id']) {
    $form['code_id'] = array(
      '#type' => 'value',
      '#value' => $game_code['code_id'],
    );

    // Search for code in catalog
    $l = sopac_get_locum();
    $tags = $l->db_query('SELECT * FROM insurge_tags WHERE tag="sg:code=' . $game_code['text'] . '"', 0);
    foreach ($tags as $tag) {
      $bibs[] = $l->get_bib_item($tag['bnum']);
    }

    if (count($bibs)) {
      $gc_bibs = '<p><h2>Game Code in Catalog:</h2><ul>';
      foreach ($bibs as $bib) {
        $gc_bibs .= '<li>' . l($bib['title'], 'catalog/record/' . $bib['_id']);
        if ($bib['author']) {
          $gc_bibs .= ', by ' . $bib['author'];
        }
        // link for deleting tag, has delay on refresh for tag removal to process
        $delURL = l('[Remove]', 'catalog/record/' . $bib['_id'], array(
          'attributes' => array(
            'target' => '_blank',
            'onclick' => 'setTimeout("document.location.reload()", 5000)',
          ),
          'query' => 'deltag=sg:code=' . $game_code['text'] . '&uid=106148',
        ));
        $gc_bibs .= '&nbsp;' . $delURL . '</li>';
      }
      $gc_bibs .= '</ul></p>';
    }
  }
  $form['text'] = array(
    '#type' => 'textfield',
    '#title' => t('Code Text'),
    '#default_value' => $game_code['text'],
    '#size' => 32,
    '#maxlength' => 255,
    '#description' => t('Keyword text for this game code (e.g. APPLESAUCE)'),
    '#required' => TRUE,
  );
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => $game_code['description'],
    '#description' => t('Description of the game code award (e.g. Attended Apple Peeling Event)'),
    '#required' => TRUE,
  );
  $form['hint'] = array(
    '#type' => 'textarea',
    '#title' => t('Hint'),
    '#default_value' => $game_code['hint'],
    '#description' => t('Does this code need a hint to figuring it out? Enter a hint here to help figure it out. (e.g. This code is a kind of food made by Mott\'s)'),
  );
  $form['points'] = array(
    '#type' => 'textfield',
    '#title' => t('Points'),
    '#default_value' => $game_code['points'],
    '#size' => 16,
    '#maxlength' => 8,
    '#description' => t('Points to be awarded for the game code (e.g. 100)'),
    '#required' => TRUE,
  );
  $form['diminishing'] = array(
    '#type' => 'checkbox',
    '#title' => t('Diminishing?'),
    '#default_value' => $game_code['diminishing'],
    '#description' => 'Each successive redemption of the game code will be worth 1 less than the previous redemption',
  );
  $form['max_redemptions'] = array(
    '#type' => 'select',
    '#title' => t('Max Redemptions'),
    '#default_value' => $game_code['max_redemptions'],
    '#options' => array(
      '0' => t('Unlimited'),
      '1' => t('Single User'),
      '2' => '2',
      '3' => '3',
      '4' => '4',
      '5' => '5',
      '10' => '10',
      '25' => '25',
      '50' => '50',
      '100' => '100',
    ),
    '#description' => t('Number of players who can receive points for this award'),
  );
  $form['valid_start'] = array(
    '#type' => 'textfield',
    '#title' => t('Code Start Time Limit'),
    '#default_value' => date('Y-m-d H:i:s', ($game_code['valid_start'] ? $game_code['valid_start'] : time())),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Date/Time for when the code becomes active (e.g. "2012-07-01 9:00 AM")'),
    '#required' => TRUE,
  );
  $form['valid_end'] = array(
    '#type' => 'textfield',
    '#title' => t('Code End Time Limit'),
    '#default_value' => $game_code['valid_end'] ? date('Y-m-d H:i:s', $game_code['valid_end']) : variable_get('summergame_gamecode_default_end', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Date/Time for when the code stops being active (e.g. "2013-08-31 12:00 AM")'),
    '#required' => TRUE,
  );
  $form['game_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Game Term'),
    '#default_value' => $game_code['game_term'] ? $game_code['game_term'] : variable_get('summergame_current_game_term', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Points will be awarded under this Game Term'),
    '#required' => TRUE,
  );
  $form['everlasting'] = array(
    '#type' => 'checkbox',
    '#title' => t('Everlasting?'),
    '#default_value' => $game_code['everlasting'],
    '#description' => 'Should this code be active in following seasons of the Game? (e.g. a code for a collection badge)',
  );
  if (!$game_code['code_id']) {
    $form['tag_bib_confirm'] = array(
      '#type' => 'radios',
      '#title' => t('Is this code for a catalog item?'),
      '#options' => array('tag_bib_yes' => t('Yes'), 'tag_bib_no' => t('No')),
      '#required' => TRUE,
    );
  }
  $form['tag_bib'] = array(
    '#type' => 'textfield',
    '#title' => t('Tag Bib Number'),
    '#size' => 32,
    '#description' => t('Enter a Bib Number/Text to automatically add this game code as a tag to that Bib record in the catalog'),
    '#suffix' => $gc_bibs,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

function summergame_code_edit_form_validate($form, &$form_state) {
  // Remove non-alphanumerics from Game Code text
  $form_state['values']['text'] = preg_replace('/[^A-Za-z0-9]/', '', $form_state['values']['text']);

  // Trim hint
  $from_state['values']['hint'] = trim($from_state['values']['hint']);

  // Check whether game code is unique
  if (!$form_state['values']['code_id']) {
    $res = db_query("SELECT code_id FROM sg_game_codes WHERE text LIKE '%s'", $form_state['values']['text']);
    if ($code = db_fetch_object($res)) {
      form_set_error('text', 'Code text is already in use. Please select another code.');
    }
  }
  if (intval($form_state['values']['points']) < 1) {
    form_set_error('points', 'Please enter a number for the point value');
  }
}

function summergame_code_edit_form_submit($form, &$form_state) {
  global $user;

  // Set end time if blank to default end date, otherwise one month out
  if (empty($form_state['values']['valid_end'])) {
    $one_month = date('Y-m-d H:i:s', strtotime('+1 month'));
    $form_state['values']['valid_end'] = variable_get('summergame_gamecode_default_end', $one_month);
  }
  if ($form_state['values']['code_id']) {
    // Update existing code
    db_query("UPDATE sg_game_codes SET text = '%s', description = '%s', hint = '%s', " .
             "points = %d, diminishing = %d, max_redemptions = %d, " .
             "valid_start = %d, valid_end = %d, game_term = '%s', everlasting = %d WHERE code_id = %d",
             strtoupper(str_replace(array("\r", "\n"), '', $form_state['values']['text'])),
             str_replace(array("\r", "\n"), '', $form_state['values']['description']),
             str_replace(array("\r", "\n"), '', $form_state['values']['hint']),
             $form_state['values']['points'],
             $form_state['values']['diminishing'], $form_state['values']['max_redemptions'],
             strtotime($form_state['values']['valid_start']), strtotime($form_state['values']['valid_end']),
             $form_state['values']['game_term'], $form_state['values']['everlasting'], $form_state['values']['code_id']);
    drupal_set_message('Game Code ' . $form_state['values']['text'] . ' Updated');
  }
  else {
    db_query("INSERT INTO sg_game_codes " .
             "(creator_uid, created, text, description, hint, points, diminishing, max_redemptions, " .
             "valid_start, valid_end, game_term, everlasting) " .
             "VALUES (%d, %d, '%s', '%s', '%s', %d, %d, %d, %d, %d, '%s', %d)",
             $user->uid, time(), strtoupper(str_replace(array("\r", "\n"), '', $form_state['values']['text'])),
             str_replace(array("\r", "\n"), '', $form_state['values']['description']),
             str_replace(array("\r", "\n"), '', $form_state['values']['hint']),
             $form_state['values']['points'], $form_state['values']['diminishing'],
             $form_state['values']['max_redemptions'], strtotime($form_state['values']['valid_start']),
             strtotime($form_state['values']['valid_end']),  $form_state['values']['game_term'],
             $form_state['values']['everlasting']);
    drupal_set_message('Game Code ' . $form_state['values']['text'] . ' Created');
  }

  // Add tag to catalog if selected
  if ($form_state['values']['tag_bib']) {
    if ($tagger_uid = variable_get('summergame_tagger_uid', '')) {
      $bib_num = $form_state['values']['tag_bib'];
      $machine_tag = 'sg:code=' . strtolower(trim($form_state['values']['text']));
      $insurge = sopac_get_insurge();
      $insurge->submit_tags($tagger_uid, $bib_num, $machine_tag);
      drupal_set_message('Game Code Tag added to Bib Number ' . l($bib_num, 'catalog/record/' . $bib_num));
    }
  }
  drupal_goto('summergame/admin');
}

/**
 * FORM: Edit a Badge
 */
function summergame_admin_badge_form($form_state, $bid = 0) {
  $form = array();

  if ($bid) {
    $badge = db_fetch_array(db_query("SELECT * FROM sg_badges WHERE bid = %d", $bid));
    $form['bid'] = array(
      '#type' => 'value',
      '#value' => $badge['bid'],
    );
  }

  $form['image'] = array(
    '#type' => 'textfield',
    '#title' => t('Image'),
    '#default_value' => $badge['image'],
    '#size' => 32,
    '#maxlength' => 255,
    '#description' => t('File name for the badge image (no extention). Place original in "files/sg_images_for_resize" to be processed.'),
  );
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => $badge['title'],
    '#size' => 64,
    '#maxlength' => 255,
    '#description' => t('Title for the Badge'),
    '#required' => TRUE,
  );
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => $badge['description'],
    '#description' => t('Description of the Badge'),
    '#required' => TRUE,
  );
  $form['level'] = array(
    '#type' => 'radios',
    '#title' => t('Level'),
    '#options' => array(
      1 => 'Level 1: Tells you explicitly what to do and requires no external sources',
      2 => 'Level 2: Direct, but brings in external sources, be explicit on search terms and material types',
      3 => 'Level 3: Difficulty increases in the clues become more obtuse, wordplay or capitalization should help you narrow your search',
      4 => 'Level 4: Operations are required to get to the next level - decoding, figuring latitute/longitude, etc.',
    ),
    '#default_value' => $badge['level'],
    '#description' => t('The level of the difficulty of the Badge'),
    '#required' => TRUE,
  );
  $form['type'] = array(
    '#type' => 'radios',
    '#title' => t('Type'),
    '#options' => array('Milestone' => 'Milestone', 'Web Search' => 'Web Search', 'Exploration' => 'Exploration', 'Event' => 'Event'),
    '#default_value' => $badge['type'],
    '#size' => 64,
    '#maxlength' => 255,
    '#description' => t('Type of Badge'),
    '#required' => TRUE,
  );
  $form['difficulty'] = array(
    '#type' => 'value',
    '#value' => $badge['difficulty'],
  );
  $form['formula'] = array(
    '#type' => 'textarea',
    '#title' => t('Badge Formula'),
    '#default_value' => $badge['formula'],
    '#description' => t("Must be one of the following formats:<ul>
  <li><strong>Badge Collection Badge:</strong> comma separated list of Badge IDs, surrounded by {} brackets, which must all be earned in order to earn this Badge. e.g. '{100,101,102,103}'</li>
  <li><strong>Ledger Multiple Badge:</strong> awarded when a term appears in the player's ledger a certain number of times. Number and Term are separated by a '::' in the formula. e.g. '10::Checkout History'</li>
  <li><strong>Collection Badge:</strong> list of ledger types or gamecodes needed for awarding a badge. Separate required AND terms with a comma, separate OR terms with a pipe. e.g. 'CODE1|CODE2,CODE3' = badge is awarded is player has CODE1 OR CODE2, AND also has CODE3</li>
</ul>"),
    '#required' => TRUE,
  );
  $form['reveal'] = array(
    '#type' => 'textfield',
    '#title' => t('Reveal'),
    '#default_value' => $badge['reveal'],
    '#size' => 32,
    '#maxlength' => 255,
    '#description' => t('Reveal this badge when the these badge IDs are earned, separate with commas'),
  );
  $form['points'] = array(
    '#type' => 'textfield',
    '#title' => t('Points'),
    '#default_value' => $badge['points'],
    '#size' => 16,
    '#maxlength' => 8,
    '#description' => t('Points to be awarded for the Badge (e.g. 100)'),
    '#required' => TRUE,
  );
  $form['points_override'] = array(
    '#type' => 'textfield',
    '#title' => t('Points Override'),
    '#default_value' => $badge['points_override'],
    '#size' => 16,
    '#maxlength' => 8,
    '#description' => t('Override Points to be awarded for the Badge (e.g. 100)'),
  );
  $form['game_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Game Term'),
    '#default_value' => $badge['game_term'] ? $badge['game_term'] : variable_get('summergame_current_game_term', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Points will be awarded under this Game Term'),
    '#required' => TRUE,
  );
  $form['game_term_override'] = array(
    '#type' => 'textfield',
    '#title' => t('Game Term Override'),
    '#default_value' => $badge['game_term_override'],
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Override Points will be awarded under this Game Term'),
  );
  $form['active'] = array(
    '#type' => 'checkbox',
    '#title' => t('Active?'),
    '#default_value' => $badge['active'],
  );
  $form['email_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Email Message'),
    '#default_value' => $badge['email_message'],
    '#description' => t('Email to be sent when Badge is awarded'),
  );
  $form['email_attachment'] = array(
    '#type' => 'textfield',
    '#title' => t('Email Attachment'),
    '#default_value' => $badge['email_attachment'],
    '#size' => 32,
    '#maxlength' => 255,
    '#description' => t('File to be attached to the award email'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

function summergame_admin_badge_form_submit($form, &$form_state) {
  if (strpos($form_state['values']['formula'], ':') !== FALSE) {
    $form_state['values']['formula'] = str_replace(array("\r", "\n"), '', $form_state['values']['formula']);
  }
  else {
    $form_state['values']['formula'] = str_replace(array("\r", "\n", ' '), '', $form_state['values']['formula']);
  }
  if ($form_state['values']['bid']) {
    // Update existing code
    db_query("UPDATE sg_badges SET image = '%s', title = '%s', description = '%s', " .
             "level = %d, type = '%s', difficulty = '%s', formula = '%s', reveal = '%s', " .
             "points = %d, points_override = '%s', game_term = '%s', " .
             "game_term_override = '%s', active = %d, email_message = '%s', " .
             "email_attachment = '%s' WHERE bid = %d",
             $form_state['values']['image'],
             str_replace(array("\r", "\n"), '', $form_state['values']['title']),
             str_replace(array("\r", "\n"), '', $form_state['values']['description']),
             $form_state['values']['level'],
             $form_state['values']['type'], $form_state['values']['difficulty'],
             $form_state['values']['formula'],
             $form_state['values']['reveal'],
             $form_state['values']['points'], $form_state['values']['points_override'],
             $form_state['values']['game_term'], $form_state['values']['game_term_override'],
             $form_state['values']['active'], $form_state['values']['email_message'],
             $form_state['values']['email_attachment'], $form_state['values']['bid']);
    drupal_set_message('Badge ' . $form_state['values']['title'] . ' Updated');
  }
  else {
    db_query("INSERT INTO sg_badges " .
             "(bid, image, title, description, level, type, difficulty, formula, reveal, points, " .
             "points_override, game_term, game_term_override, active, email_message, email_attachment) " .
             "VALUES (NULL, '%s', '%s', '%s', '%d', '%s', '%s', '%s', '%s', '%d', '%s', '%s', '%s', '%d', '%s', '%s')",
             $form_state['values']['image'],
             str_replace(array("\r", "\n"), '', $form_state['values']['title']),
             str_replace(array("\r", "\n"), '', $form_state['values']['description']),
             $form_state['values']['level'],
             $form_state['values']['type'], $form_state['values']['difficulty'],
             $form_state['values']['formula'],
             $form_state['values']['reveal'],
             $form_state['values']['points'], $form_state['values']['points_override'],
             $form_state['values']['game_term'], $form_state['values']['game_term_override'],
             $form_state['values']['active'], $form_state['values']['email_message'],
             $form_state['values']['email_attachment']);
    drupal_set_message('Badge ' . $form_state['values']['title'] . ' Created');
  }

  drupal_goto('summergame/admin');
}

/**
 * PAGE: Administer Players
 */
/*
function summergame_admin_players($search_term = '') {
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');

  if ($search_term == 'new') {
    $content .= drupal_get_form('summergame_player_form');
  }
  else {
    $search_term = strtoupper($search_term);
    $params = array();
    $new_player = array();
    $sql = "SELECT sg_players.*, users.name AS username FROM sg_players LEFT JOIN users ON sg_players.uid = users.uid WHERE 1";

    if (is_numeric($search_term)) {
      // Search phone numbers
      $sql .= " AND sg_players.phone LIKE '%%%d%%'";
      $params[] = $search_term;
      $new_player['phone'] = $search_term;
    }
    else if (preg_match('/^S?[ART]G[\d]{5}$/', $search_term)) { //SRG12345, TG12345, AG12345
      $sql .= " AND sg_players.gamecard LIKE '%%%s%%'";
      $params[] = $search_term;
      $new_player['gamecard'] = $search_term;
    }
    else if ($search_term) {
      $sql .= " AND (sg_players.name LIKE '%%%s%%' OR sg_players.nickname LIKE '%%%s%%' OR users.name LIKE '%%%s%%')";
      $params[] = $search_term;
      $params[] = $search_term;
      $params[] = $search_term;
      $new_player['name'] = $search_term;
    }

    // Run the search
    $res = db_query($sql, $params);
    $count = mysqli_num_rows($res);

    // Rerun query with OR on terms if no results
    if ($count == 0 && strpos($search_term, ' ') !== FALSE) {
      $params = array();
      $sql = "SELECT sg_players.*, users.name AS username FROM sg_players LEFT JOIN users ON sg_players.uid = users.uid WHERE (0 ";
      foreach (explode(' ', $search_term) as $term) {
        $sql .= "OR sg_players.name LIKE '%%%s%%' OR sg_players.nickname LIKE '%%%s%%' OR users.name LIKE '%%%s%%'";
        $params[] = $term;
        $params[] = $term;
        $params[] = $term;
      }
      $sql .= ")";
      $res = db_query($sql, $params);
      $count = mysqli_num_rows($res);
    }

    $content .= '<div style="float: right">' .
                drupal_get_form('summergame_player_search_form', $search_term) .
                '</div>';
    $content .= "<h2>Your search returned $count match" . ($count == 1 ? '' : 'es') . "</h2>";


    if ($count == 0) {
      // No matches, create a new player
      drupal_set_message("No existing players to match your search \"$search_term\". Create a new player with that information below:");
      $content .= drupal_get_form('summergame_player_form', $new_player);
    }
    else if ($count > 100) {
      $content .= "<h2>Your search returned more than 100 matches: ($count)<h2>";
      $content .= "<h3>Please search again</h3>";
    }
    else {
      // Found 1-100 matches, display them in a table
      while ($player = db_fetch_array($res)) {
        // Prep for display
        $player['points'] = summergame_get_player_points($player['pid']);

        $show = array();
        if ($player['leaderboard']) {
          $show[] = 'Public Leaderboard';
        }
        if ($player['myscore']) {
          $show[] = 'Player Score Page';
        }
        if ($player['public']) {
          $show[] = 'Name Display';
        }
        $rows[] = array(
          'Edit' => '[' . l('edit', 'summergame/player/edit/' . $player['pid']). ']',
          'Real Name' => l($player['name'], 'summergame/player/' . $player['pid']),
          'Player Name' => $player['nickname'],
          'Web User' => ($player['uid'] ? l($player['username'], 'user/' . $player['uid']) : ''),
          'Phone' => $player['phone'] ? $player['phone'] : '',
          'Age Group' => $player['agegroup'],
          'Gamecard' => $player['gamecard'],
          'School' => $player['school'],
          'Grade' => $player['grade'] ? $player['grade'] : '',
          //'Show On' => implode(', ', $show),
          //'Point Total' => $player['points']['total'],
        );
      }
      $content .= theme('table', array_keys($rows[0]), $rows, array('id' => 'summergame-player-search-results'));
      $content .= '<ul><li class="button green">' . l("Create New Player", 'summergame/admin/players/new') . '</li></ul>';
    }
  }

  return $content;
}
*/

/**
 * FORM: Player search form
 */
function summergame_player_search_form($form_state, $term = '') {
  $form = array();
  $form['inline'] = array(
    '#prefix' => '<div class="container-inline">',
    '#suffix' => '</div>',
  );
  $form['inline']['search_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Search for a Player'),
    '#size' => 32,
    '#maxlength' => 32,
    '#default_value' => $term,
  );
  $form['inline']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  $form['hint'] = array(
    '#value' => '<p>' .
                '<em>Search by name, partial name, cell number, or game card number.<br />' .
                '(e.g. "Anne Arbor", "Arbor", "3274200", "SRG45678")</em>' .
                '</p>',
  );

  return $form;
}

function summergame_player_search_form_submit($form, &$form_state) {
  drupal_goto('summergame/admin/players/' . $form_state['values']['search_term']);
}

/**
 * FORM: Redeem a game code
 */
function summergame_redeem_form($form_state, $player) {

  $form = array();
  $form['pid'] = array(
    '#type' => 'value',
    '#value' => $player['pid'],
  );
  $form['code_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Code Text'),
    '#size' => 32,
    '#maxlength' => 255,
    '#default_value' => ($_GET['text'] ? $_GET['text'] : ''),
    '#prefix' => '<div class="container-inline">',
    '#suffix' => '</div>',
  );
  $form['setfocus'] = array(
    '#value' => "<script type=\"text/javascript\" language=\"JavaScript\">\n" .
                "document.getElementById('edit-code-text').focus();\n" .
                "</script>",
  );

  $all_players = summergame_player_load_all($player['uid']);
  if (count($all_players) > 1) {
    $pid_options = array();
    if ($_SESSION['summergame_pid_defaults']) {
      $pid_defaults = json_decode($_SESSION['summergame_pid_defaults']);
    }
    else {
      $pid_defaults = array($player['pid']);
    }
    foreach ($all_players as $user_player) {
      $pid_options[$user_player['pid']] = ($user_player['nickname'] ? $user_player['nickname'] : $user_player['name']);
    }
    $form['pids'] = array(
      '#type' => 'checkboxes',
      '#options' => $pid_options,
      '#default_value' => $pid_defaults,
      '#title' => 'Redeem for players',
      '#prefix' => '<div class="container-inline">',
      '#suffix' => '</div>',
    );
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['cancel'] = array(
    '#value' => l('Cancel', 'summergame/player/' . $player['pid']),
  );

  return $form;
}

function summergame_redeem_form_submit($form, &$form_state) {
  $pids = array();
  if (is_array($form_state['values']['pids'])) {
    foreach ($form_state['values']['pids'] as $pid => $selected) {
      if ($pid == $selected) {
        $pids[] = $pid;
      }
    }
    $_SESSION['summergame_pid_defaults'] = json_encode($pids);
  }
  else {
    $pids[] = $form_state['values']['pid'];
  }

  foreach ($pids as $pid) {
    $status = summergame_redeem_code($pid, $form_state['values']['code_text']);
    if ($status['error']) {
      drupal_set_message($status['error'], 'error');
    }
    else if ($status['warning']) {
      drupal_set_message($status['warning'], 'warning');
    }
    else if ($status['success']) {
      drupal_set_message($status['success']);
    }
  }
  drupal_goto('summergame/player/' . $form_state['values']['pid']);
}

/**
 * FORM: Report consumption of media
 */
function summergame_consume_form($form_state, $pid, $bnum = 0) {
  $locum = sopac_get_locum();
  $form = array();
  $bib = array();

  if ($bnum) {
    if ($bib = $locum->get_bib_item($bnum)) {
      $form['bib'] = array(
        '#type' => 'value',
        '#value' => $bib,
      );
      $title = title_case($bib['title']);
      if ($bib['title_medium']) {
        $title .= ' ' . title_case($bib['title_medium']);
      }
      $finished_default = 1;
    }
  }

  $form['pid'] = array(
    '#type' => 'value',
    '#value' => $pid,
  );
  $form['mat_code'] = array(
    '#type' => 'select',
    '#title' => t("I've been enjoying this"),
    '#default_value' => $bib['mat_code'],
    '#options' => $locum->locum_config['formats'],
    '#prefix' => "<div class=\"container-inline\">",
    '#suffix' => "</div>",
  );
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Titled'),
    '#default_value' => $title,
    '#size' => 64,
    '#maxlength' => 128,
    '#description' => t('Title of the Book/Movie/Music that you are reporting'),
    '#required' => TRUE,
  );
  $form['duration'] = array(
    '#type' => 'textfield',
    '#title' => t('for this many minutes or pages (optional)'),
    '#size' => 16,
    '#maxlength' => 16,
    '#description' => t('Enter the # of pages OR the length in minutes for 1 point per page or minute! (Maximum 500 points)'),
  );
  $form['finished'] = array(
    '#type' => 'checkbox',
    '#title' => 'and I finished it!',
    '#default_value' => $finished_default,
    '#description' => 'check this box to receive a 100 point bonus for finishing this item (optional)',
  );
  $form['inline'] = array(
    '#prefix' => "<div class=\"container-inline\">",
    '#suffix' => "</div>",
  );
  $form['inline']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Score!'),
  );
  $form['inline']['cancel'] = array(
    '#value' => l('Cancel', 'summergame/player/' . $pid),
  );

  return $form;
}

function summergame_consume_form_submit($form, &$form_state) {
  $points = 0;
  $pid = $form_state['values']['pid'];
  $title = $form_state['values']['title'];
  $description = $title;
  $metadata = array('mat_code' => $form_state['values']['mat_code'],
                    'daily_limit' => 1000);

  if ($form_state['values']['bib']) {
    // Use the trusted bnum as the id instead of a user-entered id
    $metadata['bnum'] = $form_state['values']['bib']['bnum'];
  }
  else if ($form_state['values']['id']) {
    $metadata['id'] = $form_state['values']['id'];
  }
  // Duration score
  if ($form_state['values']['duration']) {
    $points += min($form_state['values']['duration'], 500);
  }
  // Finish score
  if ($form_state['values']['finished']) {
    $points += 100;
  }
  $points = summergame_player_points($pid, $points, 'Read Watched Listened', $description, $metadata);
  drupal_set_message("Earned $points points for $title");
  drupal_goto('summergame/player/' . $pid);
}

/**
 * FORM: Player information
 */
function summergame_player_form($form_state, $player = NULL) {
  drupal_add_js(drupal_get_path('module', 'summergame') . '/summergame.player.js');

  $form = array();

  if ($player['pid']) {
    $form['pid'] = array(
      '#type' => 'value',
      '#value' => $player['pid'],
    );
    if (!$player['gamecard']) {
      $game_term = variable_get('summergame_current_game_term', '');
      $signup = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d AND type = 'Signup' AND game_term = '$game_term'", $player['pid']));
      if (!$signup->lid) {
        $form['signup_eligible'] = array(
          '#type' => 'value',
          '#value' => TRUE,
        );
      }
    }
    $form['title'] = array(
      '#value' => '<p style="float: right">' .
                  l('Back to Player Score Card page', 'summergame/player/' . $player['pid']) .
                  '</p>' .
                  '<h1>Edit Summer Game Player Information</h1>',
    );
    $submit_text = 'Save Player Changes';
  }
  else {
    $form['title'] = array(
      '#value' => '<h1>Summer Game Player Signup</h1>',
    );
    $submit_text = 'Sign Up!';
  }

  $form['buttons'] = array(
    '#prefix' => '<div class="summergame-player-edit-buttons">',
    '#suffix' => '</div>',
  );
  if ($player['pid']) {
    $form['buttons']['delete'] = array(
      '#prefix' => '<div class="summergame-player-delete-link">',
      '#suffix' => '</div>',
      '#value' => l('Delete Player', 'summergame/player/delete/' . $player['pid']),
    );
  }
  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t($submit_text),
    '#attributes' => array('onClick' => 'resetDirty()'),
  );

  if ($player['pid']) {
    $cancel_path = 'summergame/player/' . $player['pid'];
  }
  else if (strpos($_GET['q'], 'admin') !== FALSE) {
    $cancel_path = 'summergame/admin';
  }
  else {
    $cancel_path = '<front>';
  }
  $form['buttons']['cancel'] = array(
    '#value' => l('Cancel', $cancel_path),
  );

  if ($player['pid'] && user_access('administer summergame')) {
    $form['admin'] = array(
      '#prefix' => '<fieldset style="float:right"><legend>STAFF ONLY</legend>',
      '#suffix' => '</fieldset>',
    );

    $form['admin']['merge_id'] = array(
      '#type' => 'textfield',
      '#title' => t('Merge this player into Player ID'),
      '#size' => 8,
      '#maxlength' => 8,
      '#description' => t("Enter another Player ID number to merge this player infomation into that player record"),
      '#prefix' => "<fieldset class=\"collapsible collapsed\"><legend>MERGE PLAYER</legend>",
      '#suffix' => "</fieldset>",
    );
  }

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#default_value' => $player['name'],
    '#size' => 30,
    '#maxlength' => 64,
    '#description' => t('Enter your real name'),
    '#required' => TRUE,
  );
  $form['nickname'] = array(
    '#type' => 'textfield',
    '#title' => t('Nickname'),
    '#default_value' => $player['nickname'],
    '#size' => 30,
    '#maxlength' => 64,
    '#description' => t('Enter an optional nickname (will be used for public display if allowed)'),
  );
  if (user_access('administer summergame')) {
    $form['phone'] = array(
      '#type' => 'textfield',
      '#title' => t('Phone Number'),
      '#default_value' => $player['phone'],
      '#size' => 30,
      '#maxlength' => 64,
      '#description' => t('Enter a phone number to play by text message (rates may apply)'),
    );
  }
  else if ($player['phone']) {
    $form['phone'] = array(
      '#type' => 'value',
      '#value' => $player['phone'],
    );
  }
/*
  $form['gamecard'] = array(
    '#type' => 'textfield',
    '#title' => t('Summer Game Card Number'),
    '#default_value' => $player['gamecard'],
    '#size' => 16,
    '#maxlength' => 16,
    '#description' => t('Did you pick up a score card? Enter its number here to help us track your progress'),
  );
  // Enter a referral code if eligible
  if (summergame_referral_available($player)) {
    $form['referred_by'] = array(
      '#type' => 'textfield',
      '#title' => t('Referred By'),
      '#size' => 16,
      '#maxlength' => 16,
      '#description' => t('Were you referred by a friend? Enter their referral code here to earn a point bonus for both of you!'),
    );
  }
*/
  // Set up privacy default values
  $privacy_defaults = array();
  if ($player['show_leaderboard']) {
    $privacy_defaults[] = 'show_leaderboard';
  }
  if ($player['show_myscore']) {
    $privacy_defaults[] = 'show_myscore';
  }
  if ($player['show_titles']) {
    $privacy_defaults[] = 'show_titles';
  }
  $form['privacy'] = array(
    '#type' => 'checkboxes',
    '#title' => 'Privacy Options',
    '#options' => array(
      'show_leaderboard' => 'Show my nickname and total score on the public leaderboard',
      'show_myscore' => 'Allow others to see my summer game scores and awards page',
      'show_titles' => 'Display the titles of Books/Movies/Music on my Score Card for others to see',
    ),
    '#default_value' => $privacy_defaults,
    '#description' => 'Select what other people can see about your Summer Game progress',
  );
  $form['agegroup'] = array(
    '#type' => 'select',
    '#title' => t('Age Group'),
    '#default_value' => $player['pid'] ? $player['agegroup'] : 'adult',
    '#options' => array(
      'youth' => 'Youth',
      'teen' => 'Teen',
      'adult' => 'Adult'
    ),
    '#description' => 'Select your age group',
    '#attributes' => array('onChange' => 'checkForSchool(this)'),
  );
  if ($player['agegroup'] == 'youth' || $player['agegroup'] == 'teen') {
    $school_style = 'display: block';
  }
  else {
    $school_style = 'display: none';
  }

  $form['school_info'] = array(
    '#prefix' => '<div id="school-details-div" style="' . $school_style . '">',
    '#suffix' => '</div>',
  );
  $school_autocomplete = array();
  $res = db_query('SELECT name FROM sg_schools ORDER BY name ASC');
  while ($school = db_fetch_object($res)) {
    $school_autocomplete[] = $school->name;
  }
  $form['school_info']['school'] = array(
    '#type' => 'autocomplete',
    '#data' => $school_autocomplete,
    '#title' => t('School'),
    '#default_value' => $player['school'],
    '#size' => 30,
    '#maxlength' => 64,
    '#description' => t('Are you a student? Please enter the name of your school to help us know'),
  );
  $form['school_info']['grade'] = array(
    '#type' => 'select',
    '#title' => t('Grade'),
    '#default_value' => $player['grade'],
    '#options' => array(
      '' => 'N/A',
      -1 => 'Preschool',
      0  => 'Kindergarten',
      1  => '1st Grade',
      2  => '2nd Grade',
      3  => '3rd Grade',
      4  => '4th Grade',
      5  => '5th Grade',
      6  => '6th Grade',
      7  => '7th Grade',
      8  => '8th Grade',
      9  => '9th Grade',
      10 => '10th Grade',
      11 => '11th Grade',
      12 => '12th Grade',
    ),
    '#description' => t('Please let us know your upcoming grade if you\'re a student'),
  );

  if (user_access('administer users')) {
    if ($summergame_user_search_path = variable_get('summergame_user_search_path', FALSE)) {
      $search_link = ' (' . l('Search for user accounts if needed', $summergame_user_search_path) . ')';
    }
    $form['uid'] = array(
      '#type' => 'textfield',
      '#title' => t('User ID'),
      '#default_value' => $player['uid'],
      '#size' => 8,
      '#maxlength' => 8,
      '#description' => t("Website User ID to connect this player") . $search_link,
    );
  }
  else if ($player['uid']) {
    $form['uid'] = array(
      '#type' => 'value',
      '#value' => $player['uid'],
    );
  }

  $form['buttons2'] = $form['buttons'];

  return $form;
}

/*
function summergame_referral_available($player) {
  $available = TRUE;

  if ($player['pid']) {
    // Check if they signed up in the current season
    $signup = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d AND type = 'Signup'", $player['pid']));
    if ($signup->game_term == variable_get('summergame_current_game_term', '')) {
      // Check if they've already received a referral bonus
      $referred = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE '%referred_by:%'", $player['pid']));
      if ($referred->lid) {
        $available = FALSE;
      }
    }
    else {
      $available = FALSE;
    }
  }

  return $available;
}
*/

function summergame_player_form_submit($form, &$form_state) {
  // Check for merge ID
  if ($form_state['values']['pid'] && $form_state['values']['merge_id']) {
    drupal_goto('summergame/admin/players/merge/' . $form_state['values']['merge_id'] . '/' . $form_state['values']['pid']);
  }

  $player_info = array(
    'name' => $form_state['values']['name'],
    'nickname' => trim($form_state['values']['nickname']),
    'gamecard' => str_replace(' ', '', strtoupper($form_state['values']['gamecard'])),
    'agegroup' => $form_state['values']['agegroup'],
    'school' => $form_state['values']['school'],
    'phone' => 'NULL', // default, handled below
  );

  // Special field handling
  if ($form_state['values']['phone']) {
    $phone = preg_replace('/[^\d]/', '', $form_state['values']['phone']);
    if (strlen($phone) == 7) {
      // preface with local area code
      $phone = '1734' . $phone;
    }
    else if (strlen($phone) == 10) {
      // preface with a 1
      $phone = '1' . $phone;
    }
    $player_info['phone'] = $phone;
  }
  $player_info['grade'] = ($form_state['values']['grade'] == '' ? 'NULL' : $form_state['values']['grade']);

  foreach ($form_state['values']['privacy'] as $name => $value) {
    $player_info[$name] = ($value ? 1 : 0);
  }

  if ($form_state['values']['uid']) {
    $player_info['uid'] = $form_state['values']['uid'];
  }

  if ($form_state['values']['pid']) {
    $player_info['pid'] = $form_state['values']['pid'];

    if ($form_state['values']['signup_eligible'] && $form_state['values']['gamecard']) {
      $signup_bonus = TRUE;
    }
  }
  else {
    $signup_bonus = TRUE;
  }

  $player = summergame_player_save($player_info);

  if (variable_get('summergame_points_enabled', 0)) {
    if ($signup_bonus) {
      $points = summergame_player_points($player['pid'], 100, 'Signup',
                                         'Signed Up for the Summer Game');
      drupal_set_message("Earned $points Summer Game points for signing up!");
    }
/*
    // Check for referral bonus
    if ($form_state['values']['referred_by']) {
      // Check for referral player
      $referring_player = summergame_player_load(array('friend_code' => $form_state['values']['referred_by']));
      if ($referring_player['pid']) {
        // Make sure no one has already gotten points for this player
        $existing_bonus = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE metadata LIKE '%referred:%s%'", $player['pid']));
        if ($existing_bonus->points) {
          drupal_set_message('Sorry, you entered a Referral Code, but your player has already been awarded points for a referral.');
        }
        else {
          summergame_player_points($player['pid'], 500, 'Referral',
                                   'Referred by Player #' . $referring_player['pid'], 'referred_by:' . $referring_player['pid']);
          summergame_player_points($referring_player['pid'], 500, 'Referral',
                                   'Referral Bonus for Player #' . $player['pid'], 'referred:' . $player['pid']);
          drupal_set_message('You were referred by Player #' . $referring_player['pid'] . ' and you each earned a 500 point bonus!');
        }
      }
      else {
        drupal_set_message('Sorry, you entered a referral code, but no player with that code exists');
      }
    }
*/
  }

  drupal_goto('summergame/player/' . $player['pid']);
}

/**
 * FORM: Delete Player form
 */
function summergame_delete_player_form(&$form_state, $pid = 0) {
  if ($player = summergame_player_load(array('pid' => $pid))) {
    $form = array();
    $form['#player'] = $player;
    $player_name = ($player['nickname'] ? $player['nickname'] : $player['name']);
    $prompt = "Are you sure you want to delete player $player_name? All associated scores and badges will be deleted as well. ";

    return confirm_form(
      $form,
      $prompt,
      'summergame/player/' . $pid,
      $prompt . ' ' . t('This action cannot be undone.'),
      t('Delete'),
      t('Cancel'),
      'summergame_delete_player_form'
    );
  }
}

function summergame_delete_player_form_submit($form, &$form_state) {
  $player = $form['#player'];
  summergame_player_delete(array('pid' => $player['pid']));
  $player_name = ($player['nickname'] ? $player['nickname'] : $player['name']);
  drupal_set_message("Deleted player $player_name and all associated points and badges");
  drupal_goto('summergame/player');
}

/**
 * FORM: Delete score form
 */
function summergame_delete_score_form(&$form_state, $pid = 0, $lid = 0) {
  $ledger = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d AND lid = %d", $pid, $lid));

  // Cannot delete points that are protected (e.g. Shop points)
  if (strpos($ledger->metadata, 'delete:no') === 0) {
    drupal_set_message('Sorry, these points are protected and cannot be deleted', 'error');
    drupal_goto('summergame/player/' . $pid);
  }

  $form = array();
  $form['#ledger'] = $ledger;
  $description = trim(preg_replace('/[\w]+:[\w]+/', '', $ledger->description));
  $prompt = "Are you sure you want to delete $ledger->points points for \"$description\"?";

  return confirm_form(
    $form,
    $prompt,
    'summergame/player/' . $pid,
    $prompt . ' ' . t('This action cannot be undone.'),
    t('Delete'),
    t('Cancel'),
    'summergame_delete_score_form'
  );
}

/**
 * FORM HANDLER: Delete score and return player to their page
 */
function summergame_delete_score_form_submit($form, &$form_state) {
  $ledger = $form['#ledger'];
  db_query("DELETE FROM sg_ledger WHERE lid = %d", $ledger->lid);
  drupal_set_message("Removed score worth $ledger->points from your player score card");
  drupal_goto('summergame/player/' . $ledger->pid);
}

/**
 * PAGE: Summer Game Player Account page
 */
/*
function summergame_player_page($pid = 0) {
  // Redirect to the right domain
  if ($sg_did = variable_get('summergame_default_domain_id', FALSE)) {
    $summergame_domain = domain_load($sg_did);
    domain_goto($summergame_domain);
  }

  global $user;

  if ($user->uid && $pid === 'extra') {
    if ($user->player['pid']) {
      drupal_set_message("Use the form below to add an extra player to your website account for another person in your household. " .
                         "You will be able to enter game codes and report reading / listening / " .
                         "watching activities for points. You will be able to switch the active player on your " .
                         "website account to specify which player receives points for online activities such as " .
                         "commenting, tagging, or writing reviews. If you wish this " .
                         "player to have a separate website identity for these online activites, please log " .
                         "out and create a new website account before signing up for the Summer Game.");
      $new_player = array('uid' => $user->uid);
      $content = drupal_get_form('summergame_player_form', $new_player);
    }
    else {
      // If no player has signed up yet, redirect to the player page
      drupal_goto('summergame/player');
    }
  }
  else {
    $pid = intval($pid);

    if ($pid) {
      $player = summergame_player_load(array('pid' => $pid));
    }
    else if ($user->player['pid']) {
      // Default to the active player if none specified
      $player = $user->player;
    }

    if ($player) {
      $player_access = summergame_player_access($player['pid']);
      // Check if player's score card is private and we don't have access
      if (!$player['show_myscore'] && !$player_access) {
        drupal_set_message("Player #$pid's Score Card is private", 'error');
        drupal_goto('<front>');
      }

      // Update checkout history for logged in user
      if ($user->uid && $player['uid'] == $user->uid && $user->profile_cohist) {
        $ch_list = db_fetch_array(db_query("SELECT * FROM sopac_lists WHERE uid = %d AND title = 'Checkout History' LIMIT 1", $user->uid));
        if ($ch_list['list_id']) {
          include_once(drupal_get_path('module', 'sopac') . '/sopac_user.php');
          sopac_update_history($ch_list);
        }
      }

      $other_players = array();
      if ($player_access && $player['uid']) {
        $all_players = summergame_player_load_all($player['uid']);

        if (count($all_players) > 1) {
          foreach ($all_players as $extra_player) {
            if ($extra_player['pid'] != $player['pid']) {
              $other_players[] = $extra_player;
            }
          }
        }
      }

      $content .= theme('summergame_player_page', $player, $player_access, $other_players);

    }
    else {
      // invalid PID or not authorized
      if ($pid) {
        drupal_set_message('Invalid Player ID: ' . $pid, 'error');
        drupal_goto('<front>');
      }
      else {
        if ($user->uid) {
          $new_player = array('uid' => $user->uid);
          $content = drupal_get_form('summergame_player_form', $new_player);
        }
        else {
          if ($catalog_domain = variable_get('summergame_catalog_domain', '')) {
            $catalog_domain = 'https://' . $catalog_domain . '/';
          }
          drupal_set_message('You must log into a website account in order to access your Player page');
          drupal_goto($catalog_domain . 'login', array('destination' => 'summergame/player'));
        }
      }
    }
  }

  return $content;
}
*/

/**
 * UTILITY: Theme player info table
 */
function theme_summergame_player_info($player) {
  $content .= '<div id="player-card">';

  // Link to Points Forms
  $content .= '<div id="player-earn-links">';
  $content .= '<h2>Earn Game Points</h2>';
  $content .= '<ul class="no-padding-left">';
  $content .= '<li class="button">' . l('I have a Game Code!', 'summergame/player/gamecode/' . $player['pid']) . '</li>';
  if (variable_get('summergame_points_enabled', 0)) {
    $content .= '<li class="button">' . l('I Read, Listened to, or Watched something!', 'summergame/player/consume/' . $player['pid']) . '</li>';
  }
  $content .= '</ul>';
  $content .= '</div>';

  // Points Summary
  $content .= '<div id="player-points-summary">';
  $summary_rows = array();
  $sg_balance = 0;
  foreach ($player['points'] as $game_term => $player_game_points) {
    if (is_array($player_game_points)) {
      $row = array();
      $row['data']['Game'] = l($game_term, '', array('fragment' => $game_term, 'external' => TRUE));
      $row['data']['Points'] = array('data' => $player_game_points['total'], 'class' => 'digits');
      if (strpos($game_term, 'SummerGame') === 0) {
        $sg_balance += $player_game_points['balance'];
        $row['class'] = 'sg-points';
      }
      $summary_rows[] = $row;
    }
  }
  $summary_rows[] = array(
    'data' => array(
      'Game' => 'Summer Game Shop Balance',
      'Points' => array('data' => '<strong>' . $sg_balance . '</strong>', 'class' => 'digits'),
    ),
    'class' => 'sg-points',
  );

  $content .= '<h2>Points Summary</h2>';
  $content .= theme('table', array_keys($summary_rows[0]['data']), $summary_rows);
  $content .= '</div>';

  // Translate privacy details
  $privacy_details .= '<ul>';
  if ($player['show_leaderboard']) {
    $privacy_details .= '<li>Show Nickname & Total Score on Public Leaderboard</li>';
  }
  if ($player['show_myscore']) {
    $privacy_details .= '<li>Show Player Page Score Card and Badges</li>';
  }
  if ($player['show_titles']) {
    $privacy_details .= '<li>Show Titles of Books/Movies/Music in the Score Card</li>';
  }
  $privacy_details .= '</ul>';

  // Determine Classic Reading Game status
  $completion_gamecode = variable_get('summergame_completion_gamecode', '');
  $row = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE '%gamecode:$completion_gamecode%'", $player['pid']));
  if ($row->lid) {
    $completed_classic = 'Yes, completed on ' . date('F j, Y', $row->timestamp);
  }
  else {
   $completed_classic = 'Not yet! Complete a game card and visit the library to receive a special prize.';
  }

  // Show cell phone options
  if (preg_match('/^[\d]{6}$/', $player['phone'])) {
    // Waiting for cell phone attachment
    $char = chr(($player['pid'] % 26) + 65);
    $player['phone'] = 'TEXT ' . $char . $player['phone'] . ' to 4AADL (42235) to connect your phone';
  }
  else if (!$player['phone']) {
    $player['phone'] = l('GENERATE CODE', 'summergame/player/gcpc/' . $player['pid']) . ' to attach your cell phone to your player.';
  }

  // Show Game Card information
  $player['gamecard'] = 'Print to complete the Classic Reading Game: ';
  $player['gamecard'] .= ' [' . l('Adult/Teen', 'summergame/pdf/adult',
                                  array('attributes' => array('target' => '_blank'))) . ' | ' .
                                l('Youth Card', 'summergame/pdf/youth',
                                  array('attributes' => array('target' => '_blank'))) . ']';

  $player_table = array(
    array('<strong>Real Name:</strong>', $player['name']),
    array('<strong>Nickname:</strong>', $player['nickname']),
    array('<strong>Cell Phone:</strong>', $player['phone']),
    array('<strong>Game Card:</strong>', $player['gamecard']),
    array('<strong>Age Group:</strong>', ucwords($player['agegroup'])),
    array('<strong>Privacy Options:</strong>', $privacy_details),
    array('<strong>Completed Classic Reading Game?:</strong>', $completed_classic),
  );

  // Lookup drupal user if admin
  if (user_access('administer summergame')) {
    if ($account = user_load(array('uid' => $player['uid']))) {
      $player_table[] = array(
        '<strong>Website User:</strong>',
        user_access('administer users') ? l($account->name, 'user/' . $account->uid) : $account->name,
      );
    }
  }

  $header = array(
    'Player Details',
    array(
      'data' => '[ ' . l('Edit Player Info', 'summergame/player/edit/' . $player['pid']) . ' ]',
      'style' => 'text-align: right',
    ),
  );

  $content .= '<div id="player-info-table">';
  //$content .= '<h2>Player Details:</h2>';
  $content .= theme('table', $header, $player_table);
  $content .= '</div>';

  // Following, Followers, Friends
  $following = array();
  $following_pids = array();
  $followers = array();
  $friends = array();

  $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE '%%fc_player:%%'", $player['pid']);
  while ($row = db_fetch_object($res)) {
    // grab player ID
    preg_match('/fc_player:([\d]+)/', $row->metadata, $matches);
    $following_player = summergame_player_load($matches[1]);
    if ($following_player['show_leaderboard']) {
      $player_name = $following_player['nickname'] ? $following_player['nickname'] : $following_player['name'];
    }
    else {
      $player_name = 'Player #' . $following_player['pid'];
    }
    if ($following_player['show_myscore'] || user_access('administer summergame')) {
      $player_name = l($player_name, 'summergame/player/' . $following_player['pid']);
    }
    $following[] = array(
      'count' => ++$following_counter,
      'player' => $player_name,
    );
    $following_pids[] = $matches[1];
  }
  $res = db_query("SELECT * FROM sg_ledger WHERE metadata LIKE 'fc_player:%d'", $player['pid']);
  while ($row = db_fetch_object($res)) {
    $follower_player = summergame_player_load($row->pid);
    if ($follower_player['show_leaderboard']) {
      $player_name = $follower_player['nickname'] ? $follower_player['nickname'] : $follower_player['name'];
    }
    else {
      $player_name = 'Player #' . $follower_player['pid'];
    }
    if ($follower_player['show_myscore'] || user_access('administer summergame')) {
      $player_name = l($player_name, 'summergame/player/' . $follower_player['pid']);
    }
    $followers[] = array(
      'count' => ++$follower_counter,
      'player' => $player_name,
    );
    if (in_array($row->pid, $following_pids)) {
      $friends[] = array(
        'count' => ++$friend_counter,
        'player' => $player_name,
      );
    }
  }

  $content .= '<div id="friend-code">';
  $content .= '<div id="friend-title"><h2>FRIEND CODE: ' . $player['friend_code'] . '</h2>';
  if (count($followers) == 0) {
    if ($player['friend_code']) {
      $action = 'I WANT A DIFFERENT';
      $hint = 'Get a new random Friend Code. You can\'t change it once you give it out.';
    }
    else {
      $action = 'GENERATE';
      $hint = "Create a random Friend Code for yourself. You can try again if you don't like it.";
    }
    $options = array('html' => TRUE, 'attributes' => array('class' => 'hint--bottom',
                                                           'data-hint' => $hint,
                                                           ));
    $content .= '[ ' . l($action . ' CODE', 'summergame/player/gfc/' . $player['pid'], $options) . ' ]';
  }
  $content .= '</div>';
  $content .= "<p>You now can have a code of your own! If another player enters your Friend Code, they'll start following you, and " .
              "you'll EACH earn 100 points. If you enter the Friend Code of any of your followers, you'll become Friends and each earn an additional " .
              "50 point bonus.</p>";
  $display_limit = 5;

  $following_header = '<span class="hint--bottom" data-hint="You have entered these players\' Friend Codes">Following: ' .
                      count($following) . '</span>';
  $content .= theme('table',
                    array(array('data' => $following_header, 'colspan' => 2)),
                    array_slice($following, 0, $display_limit));
  $followers_header = '<span class="hint--bottom" data-hint="These Players have entered your Friend Code">Followers: ' .
                      count($followers) . '</span>';
  $content .= theme('table',
                    array(array('data' => $followers_header, 'colspan' => 2)),
                    array_slice($followers, 0, $display_limit));
  $friends_header = '<span class="hint--left" data-hint="You and these Players have entered each others\' Friend Codes">Friends: ' .
                    count($friends) . '</span>';
  $content .= theme('table',
                    array(array('data' => $friends_header, 'colspan' => 2)),
                    array_slice($friends, 0, $display_limit));

  if ($following_counter > $display_limit ||
      $follower_counter > $display_limit ||
      $friend_counter > $display_limit) {
    $friend_page_link = l('See full list of Friends', 'summergame/player/friends/' . $player['pid']);
    $content .= "<p style=\"clear: left\">(Limiting display to $display_limit players. $friend_page_link.)</p>";
  }

  $content .= '</div>'; // $friend-code

  $content .= '</div>'; // #player-card

  return $content;
}

/**
 *  PAGE: List all friends
 */
/*
function summergame_player_friend_page($pid = 0) {
  global $user;
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $pid = intval($pid);

  if ($pid) {
    $player = summergame_player_load(array('pid' => $pid));
  }
  else if ($user->uid) {
    // Default to the logged in player if none specified
    $player = $user->player;
  }

  if ($player) {
    // Following, Followers, Friends
    $following = array();
    $following_pids = array();
    $followers = array();
    $friends = array();

    $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE '%%fc_player:%%'", $player['pid']);
    while ($row = db_fetch_object($res)) {
      // grab player ID
      preg_match('/fc_player:([\d]+)/', $row->metadata, $matches);
      $following_player = summergame_player_load($matches[1]);
      if ($following_player['show_leaderboard']) {
        $player_name = $following_player['nickname'] ? $following_player['nickname'] : $following_player['name'];
      }
      else {
        $player_name = 'Player #' . $following_player['pid'];
      }
      if ($following_player['show_myscore'] || user_access('administer summergame')) {
        $player_name = l($player_name, 'summergame/player/' . $following_player['pid']);
      }
      $following[] = array(
        'count' => ++$following_counter,
        'player' => $player_name,
      );
      $following_pids[] = $matches[1];
    }
    $res = db_query("SELECT * FROM sg_ledger WHERE metadata LIKE 'fc_player:%d'", $player['pid']);
    while ($row = db_fetch_object($res)) {
      $follower_player = summergame_player_load($row->pid);
      if ($follower_player['show_leaderboard']) {
        $player_name = $follower_player['nickname'] ? $follower_player['nickname'] : $follower_player['name'];
      }
      else {
        $player_name = 'Player #' . $follower_player['pid'];
      }
      if ($follower_player['show_myscore'] || user_access('administer summergame')) {
        $player_name = l($player_name, 'summergame/player/' . $follower_player['pid']);
      }
      $followers[] = array(
        'count' => ++$follower_counter,
        'player' => $player_name,
      );
      if (in_array($row->pid, $following_pids)) {
        $friends[] = array(
          'count' => ++$friend_counter,
          'player' => $player_name,
        );
      }
    }

    $content .= '<div id="friend-code">';
    $content .= '<div id="friend-title"><h2>FRIEND CODE: ' . $player['friend_code'] . '</h2>';
    if (count($followers) == 0) {
      if ($player['friend_code']) {
        $action = 'I WANT A DIFFERENT';
        $hint = 'Get a new random Friend Code. You can\'t change it once you give it out.';
      }
      else {
        $action = 'GENERATE';
        $hint = "Create a random Friend Code for yourself. You can try again if you don't like it.";
      }
      $options = array('html' => TRUE, 'attributes' => array('class' => 'hint--bottom',
                                                             'data-hint' => $hint,
                                                             ));
      $content .= '[ ' . l($action . ' CODE', 'summergame/player/gfc/' . $player['pid'], $options) . ' ]';
    }
    $content .= '</div>';
    $content .= "<p>You now can have a code of your own! If another player enters your Friend Code, they'll start following you, and " .
                "you'll EACH earn 100 points. If you enter the Friend Code of any of your followers, you'll become Friends and each earn an additional " .
                "50 point bonus.</p>";
    $following_header = '<span class="hint--bottom" data-hint="You have entered these players\' Friend Codes">Following: ' .
                        count($following) . '</span>';
    $content .= theme('table',
                      array(array('data' => $following_header, 'colspan' => 2)),
                      $following);
    $followers_header = '<span class="hint--bottom" data-hint="These Players have entered your Friend Code">Followers: ' .
                        count($followers) . '</span>';
    $content .= theme('table',
                      array(array('data' => $followers_header, 'colspan' => 2)),
                      $followers);
    $friends_header = '<span class="hint--left" data-hint="You and these Players have entered each others\' Friend Codes">Friends: ' .
                      count($friends) . '</span>';
    $content .= theme('table',
                      array(array('data' => $friends_header, 'colspan' => 2)),
                      $friends);
    $content .= '</div>'; // $friend-code
  }
  else {
    $content .= '<p>No Player Found</p>';
  }

  return $content;
}
*/

function theme_summergame_player_page($player, $player_access) {
  global $user;
  $player['points'] = summergame_get_player_points($player['pid']);
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $playername = $player['pid'] . ': ' . ($player['nickname'] ? $player['nickname'] : $player['name']);

  $content .= '<div id="summergame-player-page">';
  $content .= "<h1>Summer Game Player #$playername (" . $player['points']['career'] . " career points)</h1>";

  if ($player['uid'] == $user->uid) {
    $content .= "<p><em>That's you!</em> ";
    $extra_link = l('Sign up an extra player', 'summergame/player/extra');
    $content .= "Want to record another player's reading/listening/watching activity and game codes? $extra_link.</p>";
  }

  // Player Details
  if ($player_access) {
    // Extra Players if player has web account
    if ($player['uid']) {
      $all_players = summergame_player_load_all($player['uid']);
      // pop first player off the list to determine primary player
      $primary_player = array_shift($all_players);

      if (count($all_players)) {
        if ($player['pid'] == $primary_player['pid']) {
          // We're on the primary player page
          foreach ($all_players as $extra_player) {
            if ($extra_player['pid'] != $player['pid']) {
              // Show Extra Player Info
              $extra_player['points'] = summergame_get_player_points($extra_player['pid']);
              $extra_playername = $extra_player['nickname'] ? $extra_player['nickname'] : $extra_player['name'];
              $extra_playername = l($extra_playername, 'summergame/player/' . $extra_player['pid']);
              $content .= '<div id="summergame-extra-player">';
              $content .= "<h1>Extra Player: $extra_playername (" . $extra_player['points']['career'] . " career points)</h1>";
              $content .= '<p>[ ' . l('MAKE ACTIVE', 'summergame/player/' . $extra_player['pid'] . '/setactive') . ' ]</p>';
              //$content .= theme_summergame_player_info($extra_player);
              $content .= '</div>';
            }
          }
        }
        else {
          // We're on an extra player page
          $content .= '<p>[ ' . l('Return to main player page', 'summergame/player/' . $primary_player['pid']) . ' ]</p>';
        }
      }
    }
    $content .= theme_summergame_player_info($player);
  }

  // Player Score //////////////////////////////////////////////////////////
  foreach ($player['points'] as $game_term => $player_game_points) {
    if (is_array($player_game_points)) {
      $content .= '<div class="scorecard">';
      $content .= "<h2 class=\"title\"><a name=\"$game_term\">$game_term Scorecard</a></h2>";

      // Points
      $content .= '<div class="player-points">';
      $content .= '<h3>Points</h3>';
      $type_rows = array();
      foreach ($player_game_points['types'] as $type => $type_points) {
        $type_rows[] = array($type, array('data' => $type_points, 'class'=> 'digits'));
      }
      $type_rows[] = array('<strong>TOTAL POINTS EARNED</strong>',
                           array('data' => '<strong>' . $player_game_points['total'] . '</strong>',
                                 'class' => 'digits'));
      if (strpos($game_term, 'SummerGame') === 0) {
        $type_rows[] = array('<strong>Current Points Balance</strong>',
                             array('data' => '<strong>' . $player_game_points['balance'] . '</strong>',
                                   'class' => 'digits'));
      }

      $content .= theme('table', array('Type', 'Points'), $type_rows);

      $content .= '<ul class="scorecard-buttons">' .
                  '<li class="button">' .
                  l('See Full Scorecard', 'summergame/player/ledger/' . $player['pid'],
                    array('query' => array('term' => $game_term))) .
                  '</li>' .
                  '</ul>';

      // Date Ranges
      $latest = reset($player_game_points['ledger']);
      $earliest = end($player_game_points['ledger']);
      $content .= '<p>Points date range: <br />' .
                  date('F j, Y, g:i a', $earliest['timestamp']) . ' - <br />' .
                  date('F j, Y, g:i a', $latest['timestamp']) .
                  '</p>';

      $content .= '</div>';

      // Badges
      $content .= '<div class="player-badges">';
      $content .= '<h3>Badges</h3>';
      $sg_image_path = base_path() . file_directory_path() . '/sg_images/';
      $badge_grid = '';
      if (count($player_game_points['badges'])) {
        foreach ($player_game_points['badges'] as $badge) {
          $badge_grid .= theme_summergame_badge($badge['bid']);
        }
        $content .= $badge_grid;
      }
      else {
        $content .= "<p>This player hasn't earned any $game_term badges yet.</p>";
      }

      $content .= '</div>';

      $content .= '<div style="clear:both"></div>';
      $content .= '</div>'; // .scorecard
    }
  }
  $content .= '</div>'; // #summergame-player-page

  return $content;
}

/*
function summergame_player_ledger_page($pid = 0) {
  global $user;
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $pid = intval($pid);

  if ($pid) {
    $player = summergame_player_load(array('pid' => $pid));
  }
  else if ($user->uid) {
    // Default to the logged in player if none specified
    $player = $user->player;
  }

  if ($player) {
    $locum = sopac_get_locum();
    $player_access = summergame_player_access($player['pid']);

    if (!$player['show_myscore'] && !$player_access) {
      drupal_set_message("Player #$pid's Score Card is private", 'error');
      drupal_goto('<front>');
    }

    $rows_per_page = 100;
    $rows = array();
    $args = array($player['pid']);
    if ($_GET['term']) {
      $term_query = " AND game_term = '%s'";
      $args[] = $_GET['term'];
    }

    $locum = sopac_get_locum();
    if ($catalog_domain = variable_get('summergame_catalog_domain', '')) {
      $catalog_domain = 'http://' . $catalog_domain . '/';
    }

    $result = pager_query("SELECT * FROM sg_ledger WHERE pid = %d $term_query ORDER BY timestamp DESC",
                          $rows_per_page, 0, NULL, $args);
    while ($row = db_fetch_array($result)) {
      // Change bnum: code to a link to the bib record
      if (preg_match('/bnum:([\w-]+)/', $row['metadata'], $matches)) {
        if (preg_match('/^\d{7}$/', $matches[1])) {
          $row['description'] = '<img src="http://media.aadl.org/covers/' . $matches[1] . '_100.jpg" width="50"> ' . $row['description'];
        }
        if ($row['type'] != 'Download of the Day' || $player_access) { // Don't link to DotD records
          $row['description'] = l($row['description'],
                                  $catalog_domain . 'catalog/record/' . $matches[1],
                                  array('html' => TRUE));
        }
      }
      // Translate material code to catalog material type
      if (preg_match('/mat_code:([a-z])/', $row['metadata'], $matches)) {
        $row['description'] = 'Points for ' . $locum->locum_config['formats'][$matches[1]] .
                              ', ' . $row['description'];
      }
      // handle game codes
      if (preg_match('/gamecode:([\w]+)/', $row['metadata'], $matches)) {
        if ($player_access) {
          $row['type'] .= ': ' . $matches[1];
        }
        else {
          // Check if there is a hint for this game code
          $hint_row = db_fetch_object(db_query("SELECT hint FROM sg_game_codes WHERE text = '%s'", $matches[1]));
          if ($hint_row->hint) {
            $row['description'] = $hint_row->hint;
          }
        }
      }
      // link to nodes
      if (preg_match('/nid:([\d]+)/', $row['metadata'], $matches)) {
        if ($row['type'] != 'Download of the Day' || $player_access) { // Don't link to DotD records
          $node = node_load($matches[1]);
          $row['description'] .= ': ' . l($node->title, 'node/' . $node->nid);
          // and link to comment
          if (preg_match('/cid:([\d]+)/', $row['metadata'], $matches)) {
            $row['description'] .= ' (' .
                                   l('See comment', 'node/' . $node->nid,
                                     array('fragment' => 'comment-' . $matches[1])) .
                                   ')';
          }
        }
      }

      $table_row = array(
        'Date' => date('F j, Y, g:i a', $row['timestamp']),
        'Type' => $row['type'],
        'Description' => ($player['show_titles'] || $player_access ? $row['description'] : ''),
        'Points' => array('data' => $row['points'], 'class' => 'digits'),
      );
      if ($player_access) {
        if (strpos($row['metadata'], 'delete:no') === 0) {
          // No delete link for protected points
          $table_row['Remove?'] = '';
        }
        else {
          $table_row['Remove?'] = l('DELETE', 'summergame/player/deletescore/' . $player['pid'] . '/' . $row['lid']);
        }
      }
      $score_table[] = $table_row;
    }

    if (count($score_table)) {
      $content .= '<h2 class="title">' .
                'Player Points: ' .
                '</h2>';
      $pager = theme('pager', NULL, $rows_per_page, 0);
      $content .= $pager .  theme('table', array_keys($score_table[0]), $score_table) . $pager;
    }
    else {
      $content .= '<p>No Scores Found</p>';
    }
  }

  return $content;
}
*/

/**
 * PAGE: Player Edit page
 */
function summergame_player_edit_page($pid = 0) {
  $pid = intval($pid);
  if ($pid) {
    drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
    $player = summergame_player_load(array('pid' => $pid));
    $content .= drupal_get_form('summergame_player_form', $player);
  }
  else {
    drupal_goto('summergame/player');
  }

  return $content;
}

/**
 * PAGE: Generate Cell Phone Code
 */
/*
function summergame_player_gcpc($pid = 0) {
  if ($player = summergame_player_load(array('pid' => $pid))) {
    if (!$player['phone']) {
      // Generate a new cell phone code
      $code = 0;
      while ($code == 0) {
        $code = rand(100000, 999999);
        $collision = db_fetch_object(db_query("SELECT pid FROM sg_players WHERE phone = %d", $code));
        if ($collision->pid) {
          $code = 0;
        }
      }
      $player['phone'] = $code;
      summergame_player_save($player);
      $char = chr(($player['pid'] % 26) + 65);
      drupal_set_message('TEXT ' . $char. $code . ' to 4AADL (42235) to connect your phone');
    }
    drupal_goto('summergame/player/' . $player['pid']);
  }
  drupal_goto('summergame/player');
}
*/

/**
 * PAGE: Generate Friend Code
 */
/*
function summergame_player_gfc($pid = 0) {
  if ($player = summergame_player_load(array('pid' => $pid))) {
    // Check to see if player already has a code
    if ($player['friend_code']) {
      // Check if anyone has redeemed it already
      $res = db_query("SELECT COUNT(*) AS fcount FROM sg_ledger WHERE pid = %d AND metadata LIKE '%%fc_follower:%%'", $pid);
      $fcount = db_fetch_object($res);
      if ($fcount->fcount) {
        $followers = $fcount->fcount . ' follower' . ($fcount->fcount == 1 ? '' : 's');
        drupal_set_message("Cannot regenerate Friend Code once it has been redeemed ($followers)", 'error');
        drupal_goto('summergame/player/' . $player['pid']);
      }
    }

    // Generate a new referral code
    $nums = '34679';
    $num_max_idx = strlen($nums) - 1;
    $lines = file(drupal_get_path('module', 'summergame') . '/upgoer5words.txt');

    $code = '';
    while ($code == '') {
      $word = str_replace("'", '', trim($lines[array_rand($lines)]));
      if (strlen($word) > 3) {
        $code = strtoupper($word);
        for ($i = 0; $i < 3; $i++) {
          $code .= $nums[mt_rand(0, $num_max_idx)];
        }
        $collision = db_fetch_object(db_query("SELECT pid FROM sg_players WHERE friend_code = '%s'", $code));
        if ($collision->pid) {
          $code = '';
        }
      }
    }
    $player['friend_code'] = $code;
    summergame_player_save($player);
    drupal_set_message("Your play.aadl.org Friend Code is $code. Earn bonus points when a friend enters that code as a Game Code.");
    drupal_goto('summergame/player/' . $player['pid']);
  }
  drupal_goto('summergame/player');
}
*/

/**
 * PAGE: Game Code Redeem Page
 */
function summergame_player_redeem_page($pid = 0) {
  if ($pid) {
    if (summergame_player_access($pid)) {
      $player = summergame_player_load(array('pid' => $pid));
    }
    else {
      drupal_set_message("Invalid ID or no access for player #$pid", 'error');
      drupal_goto('summergame/player');
    }
  }
  else {
    // try to default to the logged in player
    global $user;
    $player = $user->player;
    if (empty($player)) {
      drupal_set_message("No player found for your logged in account", 'error');
      drupal_goto('summergame/player');
    }
  }

  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $content .= '<h1>Redeem a Game Code for ' . ($player['nickname'] ? $player['nickname'] : $player['name']) . '</h1>';
  $content .= '<p>You can find game codes for attending events, or by finding them around the library.</p>';
  $content .= drupal_get_form('summergame_redeem_form', $player);

  return $content;
}

/**
 * PAGE: Game Code Redeem Page
 */
function summergame_player_consume_page($pid = 0, $bnum = 0) {
  if (variable_get('summergame_points_enabled', 0)) {
    if ($pid) {
      if (summergame_player_access($pid)) {
        $player = summergame_player_load(array('pid' => $pid));
      }
      else {
        drupal_set_message("Invalid ID or no access for player #$pid", 'error');
        drupal_goto('summergame/player');
      }
    }
    else {
      // try to default to the logged in player
      global $user;
      $player = $user->player;
      if (empty($player)) {
        drupal_set_message("No player found for your logged in account", 'error');
        drupal_goto('summergame/player');
      }
    }

    $content .= '<h1>Score Points for ' . ($player['nickname'] ? $player['nickname'] : $player['name']) . ':</h1>';
    $content .= '<p>Did you read a book, listen to a CD, or watch a DVD? Enjoyed another item? Report it here to earn points:</p>';
    $content .= '<p><em>HINT: If you are reporting an item from our catalog, click the "I FINISHED THIS" button on the full catalog page to automatically fill this form.</em></p>';
    $content .= drupal_get_form('summergame_consume_form', $player['pid'], $bnum);
  }
  else {
    drupal_set_message("Sorry, earning Summer Game points for finishing items isn't active at this time.");
    drupal_goto('summergame/player');
  }

  return $content;
}

/**
 * UTILITY: Get array of all Game Terms
 */
function summergame_get_game_terms() {
  $db = \Drupal::database();
  $res = $db->query('SELECT DISTINCT game_term FROM `sg_ledger` ORDER BY game_term ASC');
  foreach ($res as $row) {
    $terms[] = $row->game_term;
  }
  return $terms;
}

/**
 * PAGE: Leaderboard Page
 */
/*
function summergame_leaderboard_page() {
  $type = $_GET['type'];
  $range = $_GET['range'];
  $staff = $_GET['staff'];
  $rows = ($_GET['rows'] ? $_GET['rows'] : 1000);

  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $args = array();

  // Switch for staff
  $staff_rid = variable_get('summergame_staff_role_id', '');

  if ($staff_rid) {
    if ($staff) {
      $lb_title .= 'Staff ';
      $staff_query = " AND users_roles.rid = $staff_rid ";
    }
    else {
      $staff_query = ' AND users_roles.rid IS NULL ';
    }
  }

  // Determine type
  $terms = summergame_get_game_terms();
  $game_term = variable_get('summergame_current_game_term', '');
  $type = (in_array($type, $terms) ? $type : $game_term);
  if ($type) {
    $type_query = 'AND sg_ledger.game_term LIKE "%s" ';
    $args[] = $type;
    $lb_title .= $type;
  }
  else {
    $type_query = '';
    $lb_title .= 'Career';
  }

  $lb_title .= ' Leaderboard';

  // Determine range
  if ($range == 'day') {
    $range_query = 'AND sg_ledger.timestamp > ' . (time() - (60 * 60 * 24)) . ' ';
    $lb_title .= ' for Today (Last 24 hours)';
  }
  else if ($range == 'week') {
    $range_query = 'AND sg_ledger.timestamp > ' . (time() - (60 * 60 * 24 * 7)) . ' ';
    $lb_title .= ' for This Week (Last 7 Days)';
  }
  else {
    $range_query = '';
    $lb_title .= ' for All Time';
  }

  $args[] = $rows;
  $leaderboard = array();

  $res = db_query('SELECT *, SUM(points) AS lb_total ' .
                  'FROM sg_ledger, sg_players ' .
                  "LEFT JOIN users_roles ON sg_players.uid = users_roles.uid AND users_roles.rid = $staff_rid " .
                  'WHERE sg_players.pid = sg_ledger.pid ' .
                  "AND sg_ledger.metadata NOT LIKE '%%leaderboard:no%%' " .
                  $type_query .
                  $range_query .
                  $staff_query .
                  'GROUP BY sg_players.pid ' .
                  'ORDER BY lb_total DESC ' .
                  'LIMIT %d', $args);

  while ($lb_player = db_fetch_array($res)) {
    if ($lb_player['show_leaderboard']) {
      $player_name = $lb_player['nickname'] ? $lb_player['nickname'] : $lb_player['name'];
    }
    else {
      $player_name = 'Player #' . $lb_player['pid'];
    }
    if ($lb_player['show_myscore'] || user_access('administer summergame')) {
      $player_name = l($player_name, 'summergame/player/' . $lb_player['pid']);
    }
    $leaderboard[] = array(
      'Place' => ++$place,
      'Player' => $player_name,
      'Total Score' => array('data' => $lb_player['lb_total'], 'class' => 'digits'),
    );
  }

  //$pager = theme('pager', NULL, $rows, 0);

  $content .= "<h1>$lb_title</h1>";
  if (count($leaderboard)) {
    $content .= $pager . theme('table', array_keys($leaderboard[0]), $leaderboard) . $pager;
  }
  else {
    $content .= "<p>No scores found</p>";
  }

  return $content;
}
*/

/*
function summergame_badge_detail_page($bid) {
  // Redirect to the right domain
  if ($sg_did = variable_get('summergame_default_domain_id', FALSE)) {
    $summergame_domain = domain_load($sg_did);
    domain_goto($summergame_domain);
  }

  $badge = db_fetch_object(db_query("SELECT * FROM sg_badges WHERE bid = %d", $bid));

  if ($badge->bid) {
    global $user;
    drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');

    if ($user->player['pid']) {
      $player_badge_status .= '<p class="player-badge-status">';
      $earned = db_fetch_array(db_query("SELECT * FROM sg_players_badges WHERE pid = %d AND bid = %d", $user->player['pid'], $badge->bid));
      if ($earned['timestamp']) {
        $player_badge_status .= 'You received this badge on ' . date('F j, Y g:i A', $earned['timestamp']);

        $share_links .= '<div class="share-links">';

        $share_links .= '<div>Share your accomplishment:</div>';

        $share_links .= '<div class="twitter-share">';
        $share_links .= '<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>';
        $share_links .= '<a href="http://twitter.com/share/?url=/" class="twitter-share-button" data-text="I earned the ' .
                                $badge->title . ' Badge in the @aadl #summergame! ' . url($_GET['q'], array('absolute' => TRUE)) .
                                ' Play along at http://play.aadl.org/." data-count="none">Tweet</a>';
        $share_links .= '</div>';

        $share_links .= '<div class="facebook-share">';
        $share_links .= <<<FBL
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<fb:like send="false" layout="standard" width="225" show_faces="true" colorscheme="light" action="like"></fb:like>
FBL;
        $share_links .= '</div>';

        $share_links .= '</div>';

        $player_badge_status .= $share_links;
      }
      else {
        $player_badge_status .= 'You have not yet earned this badge';
      }
      $player_badge_status .= '</p>';
    }

    // Handle hidden badges
    $hide_badge = FALSE;
    if ($badge->reveal) {
      if (count($user->player['bids'])) {
        $hidden_badge_titles = array();

        $required_bids = explode(',', $badge->reveal);
        foreach ($required_bids as $required_bid) {
          $required_badge = db_fetch_object(db_query("SELECT * FROM sg_badges WHERE bid = %d", $required_bid));
          $hidden_badge_titles[] = $required_badge->title;
          if (!$user->player['bids'][$required_bid]) {
            $hide_badge = TRUE;
            break;
          }
        }
        $hidden_details .= 'You must earn the following badge' .
                           (count($required_bids) == 1 ? '' : 's') .
                           ' to reveal this badge: ';
        $hidden_details .= implode(', ', $hidden_badge_titles);
      }
      else {
        // no player or player has no badges
        $hide_badge = TRUE;
      }

      if ($hide_badge) {
        $badge->image = 'hidden';
        $badge->title = 'Hidden Badge';
        $badge->description = $hidden_details;
      }
    }

    $badge_img_src = file_directory_path() . '/sg_images/' . $badge->image;
    if (file_exists($badge_img_src . '_400.png')) {
      $badge_img_src .= '_400.png';
    }
    else {
      $badge_img_src .= '_100.png';
    }
    $content .= '<div class="summergame-badge-detail">';
    $content .= '<div style="float: right; font-size: 0.75em;">[ <a href="javascript:location.reload(true)">refresh</a> ]</div>';
    $content .= l('<img src="' . base_path() . $badge_img_src . '">',
                  file_create_url($badge_img_src),
                  array('html' => TRUE));
    $content .= "<h1>$badge->title</h1>";
    $content .= "<p class=\"caption\">Difficulty: ";
    $content .= "<span class=\"badge-diff\">";
    $max_level = 4;
    $cur_level = intval($badge->level);
    $level_leftover = $max_level - $cur_level;
    for ($i = 0; $i < $cur_level; $i++) {
      $content .= "?";
    }
    $content .= "<span class=\"badge-diff-faded\">";
    for ($i = 0; $i < $level_leftover; $i++) {
      $content .= "?";
    }
    $content .= "</span></span>";
    if ($badge->type) {
      $content .= "<br>$badge->type Badge";
    }
    if ($badge->game_term) {
      $content .= "<br>Part of the $badge->game_term Game";
    }
    $content .= "</p>";
    $content .= "<p><strong>$badge->description</strong></p>";
    if ($badge->points) {
      $term = ($badge->game_term_override ? $badge->game_term_override : $badge->game_term);
      $points = ($badge->points_override ? $badge->points_override : $badge->points);
      $content .= "<p><em>$points $term point bonus when earned</em></p>";
    }

    $awarded = db_fetch_object(db_query("SELECT COUNT(pid) AS pcount FROM sg_players_badges WHERE bid = %d", $bid));
    $content .= "<p>This badge has been awarded to $awarded->pcount players</p>";

    if (!$hide_badge) {
      $player_count = 0;
      if (preg_match('/^{([\d,]+)}$/', $badge->formula, $matches)) {
        // Badge collection badge
        $formula_type = ' badges earned';
        $bids = explode(',', $matches[1]);
        $total_count = count($bids);
        foreach ($bids as $bid) {
          $badge_list .= theme_summergame_badge($bid);
        }
        $badge_count = db_fetch_object(db_query("SELECT COUNT(bid) AS bid_count FROM sg_players_badges WHERE pid = %d AND bid IN (%s)",
                                                $user->player['pid'], $matches[1]));
        $player_count = $badge_count->bid_count;
      }
      else if (strpos($badge->formula, '::') !== FALSE) {
        // Multiple Badge
        list($total_count, $text_pattern) = explode('::', $badge->formula);
        $lid_count = db_fetch_object(db_query("SELECT COUNT(lid) AS lid_count FROM sg_ledger WHERE pid = %d AND (type LIKE '%s' OR metadata LIKE 'gamecode:%s') AND game_term = '%s'",
                                                $user->player['pid'], $text_pattern, $text_pattern, $badge->game_term));
        $player_count = $lid_count->lid_count;
        $formula_type = $text_pattern . " scores in your ledger";
      }
      else {
        // Collection Badge
        $formula_type = ' criteria';
        $codes = explode(',', $badge->formula);
        $total_count = count($codes);
        $player_matches = array();
        $gc_rows = array();

        foreach ($codes as $code_id => $text_pattern) {
          $text_patterns = explode('|', $text_pattern);
          if (count($text_patterns) > 1) {
            $gc_rows[] = array('Game Code' => '<strong>One of the following:</strong>',
                               'Description' => '',
                               'Earned On' => '');
            $any_mode = TRUE;
          }
          else {
            $any_mode = FALSE;
          }

          foreach ($text_patterns as $pattern) {
            $gc_row = array('Game Code' => '',
                            'Description' => '',
                            'Earned On' => '');

            // is it a game code?
            $gc = db_fetch_object(db_query("SELECT * FROM sg_game_codes WHERE text = '%s'", $pattern));
            if ($gc->code_id) {
              $formula_type = ' game codes found';
              $gc_row['Game Code'] = '???????';
              if ($hint = $gc->hint) {
                $hint = str_replace('\'', '\x27', str_replace('"', '\x22', $hint));
                $gc_row['Description'] = "<a onclick=\"this.innerHTML = 'HINT: $hint';\">(click for hint)</a>";
              }
            }
            else {
              // not a game code
              $gc_row['Game Code'] = $pattern;
            }

            $ledger = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d AND (type LIKE '%s' OR metadata LIKE 'gamecode:%s') AND game_term = '%s' LIMIT 1",
                                               $user->player['pid'], $pattern, $pattern, $badge->game_term));
            if ($ledger->lid) {
              if (!$player_matches[$code_id]) {
                $player_count++;
                $player_matches[$code_id] = TRUE;
              }
              if ($gc->code_id) {
                $gc_row['Game Code'] = $gc->text;
                $gc_row['Description'] = $gc->description;
              }
              $gc_row['Earned On'] = date('F j, Y, g:i a', $ledger->timestamp);
            }

            if ($any_mode) {
              $gc_row['Game Code'] = '-- ' . $gc_row['Game Code'];
            }

            $gc_rows[] = $gc_row;
          }
        }
      }


      if ($user->player['pid']) {
        // Show progress bar
        if ($player_count) {
          $percentage = min(round(($player_count / $total_count) * 100), 100);
        }
        else {
          $percentage = 0;
        }
        $content .= "<h2>Your Player Progress: $percentage% ($player_count / $total_count $formula_type)</h2>";
        $content .= '<div class="meter">';
        if ($percentage == 0) {
          $percentage = 1;
        }
        $content .= "<span style=\"width: $percentage%\"></span>";
        $content .= '</div>'; // div.meter
        $content .= $player_badge_status;
      }

      if (count($gc_rows)) {
        $content .= theme('table', array_keys($gc_rows[0]), $gc_rows);
      }

      if ($badge_list) {
        $content .= '<div class="badge-collection-list">';
        $content .= '<h2>Required Badges:</h2>';
        $content .= '<div id="summergame-badges-page">';
        $content .= $badge_list;
        $content .= '</div>';
        $content .= '</div>';
      }
    }
    $content .= '</div>';
  }
  else {
    $content .= '<p>Sorry, no badge found with that ID.</p>';
  }

  return $content;
}
*/

function theme_summergame_badge() {
  global $user;
  drupal_add_css(drupal_get_path('module', 'summergame') . '/summergame.css');
  $sg_image_path = base_path() . file_directory_path() . '/sg_images/';
  $content = '';

  foreach (func_get_args() as $bid) {
    $badge = db_fetch_array(db_query("SELECT * FROM sg_badges WHERE bid = %d", $bid));
    $img_class = "summergame-badge";

    $hide_badge = FALSE;
    if ($badge['reveal']) {
      if (count($user->player['bids'])) {
        $required_bids = explode(',', $badge['reveal']);
        foreach ($required_bids as $required_bid) {
          if (!$user->player['bids'][$required_bid]) {
            $hide_badge = TRUE;
            break;
          }
        }
      }
      else {
        // no player or player has no badges
        $hide_badge = TRUE;
      }
    }

    if ($hide_badge) {
      $img_title = '???????';
      $img_src = $sg_image_path . 'hidden_100.png';
    }
    else {
      $img_title = $badge['title'];
      $img_src = $sg_image_path . $badge['image'] . '_100.png';
    }

    if ($user->player['pid']) {
      if ($user->player['bids'][$bid]) {
        $img_title .= "\n" . 'Received on ' . date('F j, Y g:i A', $user->player['bids'][$bid]);
      }
      else {
        $img_class .= ' not-earned';
      }
    }

    $img_title = htmlentities($img_title);
    $content .= l("<img class=\"$img_class\" title=\"$img_title\" src=\"$img_src\">",
                  'summergame/badge/' . $bid,
                  array('html' => TRUE)
                );
  }
  return $content;
}

/**
 * HOOK: Receive and respond to text messages
 */
function summergame_twilio_respond($incoming) {
  // Prep generic response array
  $response_template = array('uid' => twilio_lookup_user($incoming['phone']),
                             'phone' => $incoming['phone'],
                             'incoming' => 0);
  $responses = array();

  // Try to load existing player
  $player = summergame_player_load(array('phone' => $incoming['phone']));

  // Determine if text is a SummerGame text
  if (preg_match('/^[A-Za-z]([\d]{6})$/', $incoming['text'], $matches)) {
    // Cell phone merge
    if ($web_player = summergame_player_load(array('phone' => $matches[1]))) {
      // set the phone number on the web player and merge the two
      $web_player['phone'] = $incoming['phone'];
      summergame_player_save($web_player);

      $response = $response_template;
      $response['text'] .= 'Updated your player record with the phone # ' . $incoming['phone'];
      $responses[] = $response;

      if ($player['pid'] && !$player['uid']) {
        summergame_players_merge($web_player['pid'], $player['pid']);
        $response = $response_template;
        $response['text'] .= 'Merged this phone\'s player record with your website player';
        $responses[] = $response;
      }
    }
  }
  else if (strtolower($incoming['text']) == 'newplayer' ||
           strtolower($incoming['text']) == 'new player') {
    if (!$player['pid']) {
      $new_player_needed = TRUE;
    }
    else {
      $response = $response_template;
      $response['text'] .= 'Player #' . $player['pid'] . ' already attached to this phone. Enter game codes to play!';
      $responses[] = $response;
    }
  }
  else if (preg_match('/^S?[ART]G[\d]{5}$/', $incoming['text'])) {
    $game_card_text = TRUE;
    if (!$player['pid']) {
      $new_player_needed = TRUE;
    }
  }
  else if (stripos($incoming['text'], 'nick ') === 0 || stripos($incoming['text'], 'nickname ') === 0) {
    $nickname_update = TRUE;
    if (!$player['pid']) {
      $new_player_needed = TRUE;
    }
  }
  else {
    // check if it's a game code OR friend code
    $text = strtoupper(preg_replace('/[^A-Za-z0-9]/', '', $incoming['text']));
    $gc = db_fetch_object(db_query("SELECT * FROM sg_game_codes WHERE text = '%s'", $text));
    $fc_player = summergame_player_load(array('friend_code' => $text));
    if ($gc->code_id || $fc_player['pid']) {
      $game_code_text = TRUE;
      if (!$player['pid']) {
        $new_player_needed = TRUE;
      }
    }
  }

  // New Player handling
  if ($new_player_needed) {
    $new_player = array('phone' => $incoming['phone']);
    $player = summergame_player_save($new_player);
    $response = $response_template;
    $response['text'] = "New Summer Game player #" . $player['pid'] . " created for this phone.";
    $responses[] = $response;
    // Signup bonus
    $points = summergame_player_points($player['pid'], 100, 'Signup',
                                       'Signed Up for the Summer Game', 'via:txt');
    $response = $response_template;
    $response['text'] = "Earned $points Summer Game points for signing up!";
    $responses[] = $response;
  }

  if ($game_card_text || $game_code_text) {
    // Process results for ALL Player records with this number
    $res = db_query('SELECT pid FROM sg_players WHERE phone = %d', $incoming['phone']);
    while ($player_info = db_fetch_object($res)) {
      $player = summergame_player_load(array('pid' => $player_info->pid));
      // Associate a gamecard with the player if a game card ID
      if ($game_card_text) {
        $player['gamecard'] = $incoming['text'];
        summergame_player_save($player);
        $response = $response_template;
        $response['text'] .= 'Updated your player record with the scorecard ID ' . $incoming['text'];
        $responses[] = $response;
      }
      else {
        // Try to redeem text as a game code
        $status = summergame_redeem_code($player['pid'], $incoming['text']);

        if ($status['success'] || $status['error']) {
          $response = $response_template;
          $response['text'] .= $status['success'] . $status['error'];
          $responses[] = $response;
        }
        if (variable_get('summergame_dod_enabled', FALSE)) {
          if ($status['success']) {
            // Check how many DoD game codes they have received
            $res = db_query("SELECT COUNT(*) AS dod_count FROM sg_ledger WHERE pid = %d " .
                            "AND game_term = 'DoOrDiag' AND " .
                            "((metadata LIKE '%%gamecode:%%' AND metadata NOT LIKE '%%gamecode:READY%%') " .
                            "OR (type = 'New Track' AND points > 0))",
                            $player['pid']);
            $row = db_fetch_object($res);
            if ($row->dod_count == 4) {
              $response = $response_template;
              $response['text'] .= "You have completed the short game! Go receive a prize or continue playing!";
              $responses[] = $response;
            }
            else if ($row->dod_count == 10) {
              $response = $response_template;
              $response['text'] .= "You have completed the long game! Go get your prize!";
              $responses[] = $response;
            }
          }
        }
        // If not recognized, no response to allow other handlers to respond
      }
    }
  }
  // New Nickname
  else if ($nickname_update) {
    $player['nickname'] = substr($incoming['text'], strpos($incoming['text'], ' ') + 1);
    $player['show_leaderboard'] = 1;
    $player = summergame_player_save($player);
    $response = $response_template;
    $response['text'] .= 'Your Player nickname has been set to ' . $player['nickname'];
    $responses[] = $response;
  }
  // Lego Contest
  else if (variable_get('summergame_lego_enabled', FALSE)) {
    $text = strtoupper($incoming['text']);
    if (preg_match('/^L[PKEMHA][\d]{3}$/', $text)) {
      require_once(variable_get('summergame_libphp_path', '') . 'contrib/redisent/redisent.php');
      $redis = new Redisent('multivac');
      // Set category vote for this phone
      $redis->set('lego_vote:' . $text[1] . ':' . $incoming['phone'], $text);
      $response = $response_template;
      $response['text'] .= 'Your vote has been recorded for Group ' . $text[1];
      $responses[] = $response;
    }
  }
  // Do Or Diag
  else if (variable_get('summergame_dod_enabled', FALSE)) {
    $text = strtoupper($incoming['text']);
    if ($dod_response = summergame_dod_response($text, $player['pid'])) {
      $response = $response_template;
      $response['text'] .= $dod_response;
      $responses[] = $response;

      // Check how many DoD game codes they have received
      $res = db_query("SELECT COUNT(*) AS dod_count FROM sg_ledger WHERE pid = %d " .
                      "AND game_term = 'DoOrDiag' AND " .
                      "((metadata LIKE '%%gamecode:%%' AND metadata NOT LIKE '%%gamecode:READY%%') " .
                      "OR (type = 'New Track' AND points > 0))",
                      $player['pid']);
      $row = db_fetch_object($res);
      if ($row->dod_count == 4) {
        // Check if they have finished the short game
        $ledger = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d " .
                                           "AND game_term = 'DoOrDiag' AND " .
                                           "Type LIKE 'Completed Short Game'", $player['pid']));
        if (!$ledger->lid) {
          summergame_player_points($player['pid'], 0, 'Completed Short Game',
                                   'You answered four Do Or Diag questions', '', 'DoOrDiag');
          $response = $response_template;
          $response['text'] .= "You have completed the short game! Go receive a prize or continue playing!";
          $responses[] = $response;
        }
      }
      else if ($row->dod_count == 10) {
        // Check if they have finished the long game
        $ledger = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d " .
                                           "AND game_term = 'DoOrDiag' AND " .
                                           "Type LIKE 'Completed Long Game'", $player['pid']));
        if (!$ledger->lid) {
          summergame_player_points($player['pid'], 0, 'Completed Long Game',
                                   'You answered ten Do Or Diag questions', '', 'DoOrDiag');
          $response = $response_template;
          $response['text'] .= "You have completed the long game! Go get your prize!";
          $responses[] = $response;
        }
      }
    }
  }

  // Check if Trivia is active
  if (variable_get('summergame_trivia_active', FALSE) && !count($responses) && $player['pid']) {
    $guess = $incoming['text'];
    $answer = variable_get('summergame_trivia_answer', '');
    $trivia_game_term = variable_get('summergame_trivia_game_term', '');

    db_query("INSERT INTO sg_trivia_guesses (guess) VALUES ('%s')", $guess);
    $guesstext = strtoupper(preg_replace('/[^A-Za-z0-9]/', '', $incoming['text']));
    if (stripos($guesstext, $answer) !== FALSE) {
      // Correct Answer
      if (db_query("INSERT INTO sg_trivia_correct (phone) VALUES ('%d')", $incoming['phone'])) {
        $place = db_last_insert_id('sg_trivia', 'id');
        $points = 101 - $place;

        summergame_player_points($player['pid'], $points, 'Correct Trivia Answer',
                                 "Correct Answer #$place: $guess", '', $trivia_game_term);

        $response = $response_template;
        $response['text'] = "Your answer of \"$guess\" is Correct Answer #$place! You earn $points points.";
      }
      else {
        // Duplicate correct answer
        $response = $response_template;
        $response['text'] = "Duplicate answer \"$guess\" received.";
      }
/*
      if ($place == 1) {
        $response['text'] .= ' Please see a staff member to claim your prize';
      }
*/
      $responses[] = $response;
    }
    else {
      $response = $response_template;
      $response['text'] = "Sorry, your answer of \"$guess\" was incorrect. Please try again";
      $responses[] = $response;
    }
  }

  if (count($responses)) {
    return $responses;
  }
}

function summergame_dod_response($text, $pid) {
  $response = '';

  // Grab DoD Data from Couch
  $libphp_path = variable_get('summergame_libphp_path', '');
  include_once($libphp_path . 'contrib/PHP-on-Couch/lib/couch.php');
  include_once($libphp_path . 'contrib/PHP-on-Couch/lib/couchClient.php');
  include_once($libphp_path . 'contrib/PHP-on-Couch/lib/couchDocument.php');
  $couch = new couchClient('COUCHDB_DSN_STRING', 'doordiag');

  $track_lookup = array();
  try {
    $tracks = $couch->getDoc('tracks');
    foreach ($tracks as $code => $track) {
      if ($code[0] != '_') {
        $track_lookup[$code] = $track;
      }
    }
  }
  catch (Exception $e) {
    echo "Something weird happened: ".$e->getMessage()." (errcode=".$e->getCode().")\n";
  }

  if ($new_track = $track_lookup[$text]) {
    // check if they've already received points for this track
    $row = db_fetch_array(db_query("SELECT * FROM sg_ledger WHERE pid = %d " .
                                   "AND metadata LIKE '%%track:%s%%' AND points > 0",
                                   $pid, $new_track));
    $points = ($row['lid'] ? 0 : 500);

    summergame_player_points($pid, $points, 'New Track', "Started the $new_track Track",
                             'track:' . $new_track, 'DoOrDiag');
    $response = "You just received $points Do Or Diag points, and you are now on the $new_track trivia track.";
  }
  else try {
    $questions = $couch->getDoc($text);

    // Determine player track
    $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND game_term = 'DoOrDiag' " .
                    "AND metadata LIKE '%track:%' ORDER BY timestamp DESC LIMIT 1", $pid);
    $row = db_fetch_array($res);
    preg_match('/track:([\w]+)/', $row['metadata'], $matches);
    $track = $matches[1];

    $response = $questions->$track;
  }
  catch (Exception $e) {
    // no couch doc ID matches that text
  }

  return $response;
}

/**
 * HOOK: Add points when someone comments
 */
function summergame_comment($action, $op) {
  if (variable_get('summergame_points_enabled', 0)) {
    if ($op == 'publish' || $op == 'delete') {
      // Cast $action to array if it is an object
      if (is_object($action)) {
        $action = get_object_vars($action);
      }
      $players = summergame_player_load_all($action['uid']);
      if (count($players)) {
        // Check if they have already received points for this comment
        $pids = array();
        foreach ($players as $player) {
          $pids[] = $player['pid'];
        }
        $ledger = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid IN (%s) and metadata LIKE '%%cid:%d%%'",
                                           implode(',', $pids), $action['cid']));
        if ($op == 'publish' && !$ledger->lid) {
          $metadata = array(
            'nid' => $action['nid'],
            'cid' => $action['cid'],
          );
          $account = user_load($action['uid']);
          $player = summergame_player_load($account->sg_active_pid ? $account->sg_active_pid : min($pids));
          if ($points = summergame_player_points($player['pid'], 50, 'Added Comment',
                                                 'Commented on a website post', $metadata)) {
            $player_name = $player['nickname'] ? $player['nickname'] : $player['name'];
            $others_message = summergame_other_players_message();
            $scorecard_link = l($points . ' Summer Game points', 'summergame/player/' . $player['pid']);
            drupal_set_message("Player $player_name earned $scorecard_link for commenting on a website post.$others_message");
          }
        }
        else if ($op == 'delete' && $ledger->lid) {
          db_query("DELETE FROM sg_ledger WHERE lid = %d", $ledger->lid);
          drupal_set_message("Removed Summer Game points for deleted comment");
        }
      }
    }
  }
}

/**
 * HOOK: Add points when someone views a node
 */
/*
function summergame_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  if (variable_get('summergame_points_enabled', 0)) {
    global $user;
    if ($user->uid && $op == 'view' && $page) {
      // check if user has already received points for viewing this node
      if ($player = summergame_player_load(array('uid' => $user->uid))) {
        $res = db_query("SELECT lid FROM sg_ledger WHERE pid = %d AND metadata = 'Read a Post' " .
                        "AND description LIKE '%%nid:%d' LIMIT 1",
                        $player['pid'], $node->nid);
        $rate_count = db_fetch_object($res);
        if (!$rate_count->lid) {
          $node_link = l($node->title, 'node/' . $node->nid);
          $points = summergame_player_points($player['pid'], 10, 'Read a Post',
                                             'Read a website post: ' . $node_link, 'nid:' . $node->nid);
          $points_link = l($points . ' Summer Game points', 'summergame/player');
          drupal_set_message("Earned $points_link for reading a website post");
        }
      }
    }
  }
}
 */

/**
 * UTILITY: Determine access to a player record
 */
function summergame_player_access($pid) {
  $access = FALSE;

  $user = \Drupal::currentUser();
  if ($user->hasPermission('administer summergame')) {
    $access = TRUE;
  }
  else {
    if ($user->uid) {
      $player = summergame_player_load($pid);
      if ($user->uid == $player['uid']) {
        $access = TRUE;
      }
    }
  }
  return $access;
}

/**
 * UTILITY: Lookup a player record (based on the user_load function)
 */
function summergame_player_load($player_info = []) {
  // Dynamically compose a SQL query:
  $query = [];
  $params = [];

  // Default to pid lookup
  if (is_numeric($player_info)) {
    $player_info = ['pid' => $player_info];
  }
  else if (!is_array($player_info)) {
    return FALSE;
  }

  foreach ($player_info as $key => $value) {
    if ($value) {
      if ($key == 'pid' || $key == 'phone' || $key == 'uid') {
        $query[] = "$key = :$key";
      }
      else {
        $query[] = "LOWER($key) = LOWER(:$key)";
      }
      $params[":$key"] = $value;
    }
  }

  if (count($params)) {
    $db = \Drupal::database();
    $result = $db->query('SELECT * FROM {sg_players} WHERE ' . implode(' AND ', $query) .
                         ' ORDER BY pid ASC LIMIT 1', $params);
    $player = $result->fetchAssoc();
  }

  if ($player['pid']) {
    // Load badge ids
    $result2 = $db->query('SELECT * FROM {sg_players_badges} WHERE pid = ' . $player['pid']);
    while ($badge = $result2->fetchObject()) {
      $player['bids'][$badge->bid] = $badge->timestamp;
    }
    return $player;
  }
  else {
    return FALSE;
  }
}

/**
 * UTILITY: Load ALL players associated with a user
 */
function summergame_player_load_all($uid) {
  $db = \Drupal::database();
  $result = $db->query('SELECT * FROM sg_players WHERE uid = ' . (int) $uid . ' ORDER BY pid ASC');
  $players = [];
  while ($player = $result->fetchAssoc()) {
    $players[] = $player;
  }

  return $players;
}

/**
 * PAGE CALLBACK: Set active player for a user
 */
function summergame_player_set_active($pid) {
  if ($player = summergame_player_load($pid)) {
    if ($player['uid']) {
      if ($account = user_load($player['uid'])) {
        user_save($account, array('sg_active_pid' => $pid));
        drupal_set_message('Player #' . $pid . ' (' . $player['nickname'] . ') is now the active player for the website account <em>' .
                           $account->name . '</em>. Online activities that earn points (comments, ratings, reviews, etc.) will now be awarded ' .
                           'to this player.');
      }
      else {
        drupal_set_message('Cannot load the website account associated with Player #' . $pid, 'warning');
      }
    }
    else {
      drupal_set_message('No website user associated with Player #' . $pid, 'warning');
    }
  }
  else {
    drupal_set_message('No player found with Player #' . $pid);
  }
  drupal_goto('summergame/player/' . $pid);
}

/**
 * UTILITY: Load player points
 */
function summergame_get_player_points($pid, $game_term = '', $type = '') {
  $player_points = [
    'career' => 0,
  ];

  $query = 'SELECT * FROM sg_ledger WHERE pid = :pid';
  $args = [':pid' => $pid];
  if ($game_term) {
    $query .= " AND game_term = :game_term";
    $args[':game_term'] = $game_term;
  }
  if ($type) {
    $query .= " AND type = :type";
    $args[':type'] = $type;
  }
  $query .= ' ORDER BY timestamp DESC';

  $db = \Drupal::database();
  $res = $db->query($query, $args);

  while ($row = $res->fetchAssoc()) {
    $game_term = $row['game_term'];
    $type = $row['type'];
    $player_points[$game_term]['ledger'][] = $row;
    $player_points[$game_term]['balance'] += $row['points'];
    $player_points[$game_term]['types'][$type] += $row['points'];
    if ($row['points'] > 0 && strpos($row['metadata'], 'leaderboard:no') === FALSE) {
      // Don't count non-leaderboard points in the total
      $player_points[$game_term]['total'] += $row['points'];
      $player_points['career'] += $row['points'];
    }
  }

  // Sort type points
  foreach ($player_points as $game_term => &$details) {
    if (is_array($details['types'])) {
      arsort($details['types']);
    }
  }

  // Get badges
  $res = $db->query("SELECT * FROM sg_players_badges, sg_badges " .
                    "WHERE sg_players_badges.pid = :pid AND sg_players_badges.bid = sg_badges.bid " .
                    "ORDER BY sg_players_badges.timestamp ASC", [':pid' => $pid]);
  while ($badge = $res->fetchAssoc()) {
    $game_term = $badge['game_term'];
    $player_points[$game_term]['badges'][] = $badge;
  }

  return $player_points;
}

/**
 * UTILITY: Save a player record
 */
function summergame_player_save($player) {
  $db = \Drupal::database();

  if ($pid = $player['pid']) {
    // Update existing player record
    unset($player['pid']);
    $db->update('sg_players')->fields($player)->condition('pid', $pid)->execute();
  }
  else {
    // New player record
    $pid = $db->insert('sg_players')->fields($player)->execute();
  }

  return summergame_player_load(array('pid' => $pid));
}

/**
 * UTILITY: Delete a player record
 *
 * Uses the same arguments as summergame_player_load
 */
function summergame_player_delete($player_info) {
  if ($player = summergame_player_load($player_info)) {
    // Delete points
    db_query("DELETE FROM sg_ledger WHERE pid = %d", $player['pid']);
    // Delete badges
    db_query("DELETE FROM sg_players_badges WHERE pid = %d", $player['pid']);
    // Delete team memberships
    db_query("DELETE FROM sg_players_teams WHERE pid = %d", $player['pid']);
    // Delete player info
    db_query("DELETE FROM sg_players WHERE pid = %d", $player['pid']);
    // Check if active player, reset if so
    if ($player->uid) {
      $account = user_load($player->uid);
      if ($account->sg_active_pid == $player->pid) {
        user_save($account, array('sg_active_pid' => NULL));
      }
    }
  }
}

/**
 * UTILITY: Redeem a game code for a player
 */
function summergame_redeem_code($pid, $code_text) {
  // Remove non-alphanumerics from Game Code text and convert to upper case
  $code_text = strtoupper(preg_replace('/[^A-Za-z0-9]/', '', $code_text));

  // Check for Friend Code
  if ($fc_player = summergame_player_load(array('friend_code' => $code_text))) {
    // Player Found
    if ($fc_player['pid'] == $pid) {
      return array('error' => "Player #$pid cannot redeem own Friend Code");
    }
    // Check if player has already redeemed this code
    else {
      $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_player:%d'", $pid, $fc_player['pid']);
      if ($existing = db_fetch_object($res)) {
        $existing_date = date('F j, Y, g:i a', $existing->timestamp);
        return array('error' => "Friend Code for Player #" . $fc_player['pid'] . " already redeemed on $existing_date");
      }
    }
    if (variable_get('summergame_points_enabled', 0)) {
      // Award points to Friend Code owner and to current player
      $fc_points = 100;
      summergame_player_points($fc_player['pid'], $fc_points, 'Friend Code', 'Player #' . $pid . ' followed you!', 'fc_follower:' . $pid);
      $points = summergame_player_points($pid, $fc_points, 'Friend Code', 'You followed Player #' . $fc_player['pid'] . '!', 'fc_player:' . $fc_player['pid']);
      $message = "You redeemed Player #" . $fc_player['pid'] . "'s Friend Code for $points points!";
      // Check if reciprocal; award bonus if friends
      $ledger = db_fetch_object(db_query("SELECT lid FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_player:%d' LIMIT 1",
                                         $fc_player['pid'], $pid));
      if ($ledger->lid) {
        $bonus_points = 50;
        summergame_player_points($fc_player['pid'], $bonus_points, 'Friend Code', 'You and Player #' . $pid . ' are now friends!', 'fc_friend:' . $pid);
        $points = summergame_player_points($pid, $bonus_points, 'Friend Code', 'You and Player #' . $fc_player['pid'] . ' are now friends!', 'fc_friend:' . $fc_player['pid']);
        $message .= '. You and Player #' . $fc_player['pid'] . ' are now friends; you both get a ' . $bonus_points . ' point bonus!';
      }
      return array('success' => $message);
    }
    else {
      return array('warning' => "Friend Codes can only be entered during Summer Game");
    }
  }
  else {
    // Check for Game Code
    $code = db_fetch_object(db_query("SELECT * FROM sg_game_codes WHERE text = '%s'", $code_text));
    if ($code->code_id) {
      // Existing code
      $now = time();
      if ($now < $code->valid_start) {
        $start_date = date('F j, Y, g:i a', $code->valid_start);
        return array('error' => "Code \"$code->text\" is not yet valid. It will activate on $start_date");
      }
      else if ($now > $code->valid_end) {
        $end_date = date('F j, Y, g:i a', $code->valid_end);
        return array('error' => "Code \"$code->text\" is no longer valid. It expired on $end_date");
      }
      else if ($code->max_redemptions && ($code->num_redemptions >= $code->max_redemptions)) {
        return array('error' => "Code \"$code->text\" has reached maximum number of redemptions");
      }
      else {
        // check if player has already redeemed this code
        $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'gamecode:%s'", $pid, $code->text);
        if ($existing = db_fetch_object($res)) {
          $existing_date = date('F j, Y, g:i a', $existing->timestamp);
          return array('error' => "Code \"$code->text\" already redeemed on $existing_date");
        }
      }
      // Go ahead and redeem
      db_query("UPDATE sg_game_codes SET num_redemptions = num_redemptions + 1 WHERE code_id = %d", $code->code_id);

      if ($code->points_override) {
        $code->points = $code->points_override;
      }
      else if ($code->diminishing) {
        // Adjust points if diminishing
        $code->points -= $code->num_redemptions;
      }
      if ($code->game_term_override) {
        $code->game_term = $code->game_term_override;
      }

      $points = summergame_player_points($pid, $code->points, 'Game Code', $code->description, 'gamecode:' . $code->text, $code->game_term);
      $message = "Redeemed code \"$code->text\" for $points $code->game_term points";
      if ($code->description) {
        $message .= ': ' . $code->description;
      }
      return array('success' => $message);
    }
    else {
      return array('warning' => "Code is not recognized");
    }
  }
}

/**
 * UTILITY: Get count of ledger rows for a player
 */
function summergame_get_ledger_count($pid, $filter = '') {
  // Dynamically compose a SQL query:
  $query = array('pid = %d');
  $params = array($pid);

  if (is_array($filter)) {
    foreach ($filter as $key => $value) {
      $query[] = "$key LIKE '%%%s%%'";
      $params[] = $value;
    }
  }

  $result = db_query('SELECT COUNT(*) AS ledger_count FROM sg_ledger WHERE ' .
                     implode(' AND ', $query), $params);
  $count = db_fetch_object($result);

  return $count->ledger_count;
}

/**
 * UTILITY: Apply points to a player
 */
function summergame_player_points($pid, $points, $type, $description = '', $metadata = '', $game_term = '') {
  $db = \Drupal::database();

  if (is_array($metadata)) {
    if ($limit = $metadata['daily_limit']) {
      $day_start = mktime(0, 0, 0);

      $sql = "SELECT SUM(points) AS total FROM sg_ledger " .
             "WHERE pid = :pid " .
             "AND timestamp > %d " .
             "AND metadata LIKE '%:limit%'";
      $row = $db->query($sql, [':pid' => $pid, ':timestamp' => $day_start, ':limit' => 'daily_limit:' . $limit])->fetchObject();

      $total = $row->total + $points;
      if ($total > $limit) {
        // If over the limit, cap the point total at the daily limit
        $overage = $total - $limit;
        drupal_set_message("Sorry, your score of $points brings you over the daily limit of $limit by $overage. You may report those additional points tomorrow.", 'warning');
        $points -= $overage;
      }
      else {
        drupal_set_message("You have earned $total points of your daily limit of $limit for this type of scoring");
      }
    }

    // Convert metadata to string
    $md_string = '';
    if (count($metadata)) {
      foreach ($metadata as $key => $value) {
        if (!is_numeric($key)) {
          $md_string .= $key . ':' . $value . ' ';
        }
        else {
          $md_string .= $value . ' ';
        }
      }
    }
    $metadata = trim($md_string);
  }

  // Set game_term
  if (empty($game_term)) {
    $game_term = \Drupal::config('summergame.settings')->get('summergame_current_game_term');
  }

  $db->insert('sg_ledger')->fields([
    'pid' => $pid,
    'points' => $points,
    'type' => $type,
    'metadata' => $metadata,
    'description' => $description,
    'game_term' => $game_term,
    'timestamp' => time(),
  ])->execute();

  // Check if the new points affect any badges
  if ($messages = summergame_player_check_badges($pid, $game_term)) {
    foreach ($messages as $message) {
      drupal_set_message($message);
    }
  }

  return $points;
}

function summergame_other_players_message() {
  // Check for other players if awarding points to logged in user
  global $user;
  $message = '';
  if ($user->other_players) {
    $other_links = array();
    foreach ($user->other_players as $other_player) {
      $other_links[] = l(($other_player['nickname'] ? $other_player['nickname'] : $other_player['name']),
                         'summergame/player/' . $other_player['pid'] . '/setactive');
    }
    $message .= ' (Make another player active?: ' .
                implode(' OR ', $other_links) . ')';
  }

  return $message;
}

/**
 * UTILITY: Check player for new badges
 */
function summergame_player_check_badges($pid, $game_term) {
  $pid = (int) $pid;
  $db = \Drupal::database();
  $messages = [];

  $player_bids = [];
  $res = $db->query('SELECT * FROM sg_players_badges WHERE pid = ' . $pid);
  while ($player_badge = $res->fetchObject()) {
    $player_bids[] = $player_badge->bid;
  }

  $res = $db->query("SELECT * FROM sg_badges WHERE game_term = :game_term " .
                    "AND active = 1 AND formula != '' ORDER BY bid ASC", [':game_term' => $game_term]);
  while ($badge = $res->fetchObject()) {
    if (!in_array($badge->bid, $player_bids)) {
      $awarded = FALSE;
      if (preg_match('/^{([\d,]+)}$/', $badge->formula, $matches)) {
        // Badge collection badge
        $eligible = TRUE;
        foreach (explode(',', $matches[1]) as $formula_bid) {
          if (!in_array($formula_bid, $player_bids)) {
            $eligible = FALSE;
            break;
          }
        }
        if ($eligible) {
          $awarded = summergame_player_award_badge($pid, $badge->bid);
        }
      }
      else if (strpos($badge->formula, '::')) {
        // Multiple of a ledger type formula
        list($count_limit, $text_pattern) = explode('::', $badge->formula);
        $lid_count = $db->query("SELECT COUNT(lid) AS lid_count FROM sg_ledger WHERE pid = $pid " .
                                "AND (type LIKE :text_pattern OR metadata LIKE :gamecode_pattern) AND game_term = :game_term",
                                [':text_pattern' => $text_pattern, ':gamecode_pattern' => "gamecode:$text_pattern%", ':game_term' => $badge->game_term]);
        if ($lid_count->lid_count >= $count_limit) {
          $awarded = summergame_player_award_badge($pid, $badge->bid);
        }
      }
      else {
        // Collection Badge
        $eligible = TRUE;
        foreach (explode(',', $badge->formula) as $text_pattern) {
          $query = "SELECT lid FROM sg_ledger WHERE pid = $pid AND (";
          $args = array($pid);

          $text_patterns = explode('|', $text_pattern);
          foreach ($text_patterns as &$pattern) {
            $args[] = $pattern;
            $args[] = $pattern;
            $pattern = "(type LIKE '%s' OR metadata LIKE 'gamecode:%s')";
          }
          $query .= implode(' OR ', $text_patterns);

          $query .= ") AND game_term = '%s' LIMIT 1";
          $args[] = $badge->game_term;

          $ledger = db_fetch_object(db_query($query, $args));

          if (!$ledger->lid) {
            $eligible = FALSE;
            break;
          }
        }
        if ($eligible) {
          $awarded = summergame_player_award_badge($pid, $badge->bid);
        }
      }

      if ($awarded) {
        $badge_detail_link = l('Badge Detail Page', 'summergame/badge/' . $badge->bid,
                               array('html' => TRUE,
                                     'query' => array('lightbox' => 1),
                                     'attributes' => array('rel' => 'lightframe'),
                                    )
                              );
        $messages[] = "Earned the $badge->title Badge! Share your accomplishment on Twitter or Facebook on the $badge_detail_link";
        $player_bids[] = $badge->bid;
        // check if a bonus should be applied
        if ($badge->points) {
          // check for points override
          if ($badge->points_override) {
            $badge->points = $badge->points_override;
          }
          if ($badge->game_term_override) {
            $badge->game_term = $badge->game_term_override;
          }
          else if (empty($badge->game_term)) {
            $badge->game_term = variable_get('summergame_current_game_term', '');
          }

          // Handle multiple bonuses
          $points_values = explode(',', $badge->points);
          $game_terms = explode(',', $badge->game_term);
          $points = 0;

          foreach ($game_terms as $i => $game_term) {
            if ($points_values[$i]) {
              $points = $points_values[$i];
            }
            db_query("INSERT INTO sg_ledger (pid, points, type, metadata, description, game_term, timestamp) " .
                     "VALUES (%d, %d, '%s', '%s', '%s', '%s', %d)",
                     $pid, $points, 'Badge Bonus', $metadata, "Earned the $badge->title Badge",
                     $game_term, time());
            $messages[] = "Received $points bonus $game_term points for earning the $badge->title Badge";
          }
        }
        // check if an email should be sent to awardee
        if ($badge->email_message) {
          // Find email address attached to user account
          $u = db_fetch_object(db_query("SELECT users.mail AS mail FROM users, sg_players WHERE users.uid = sg_players.uid AND sg_players.pid = %d", $pid));
          if ($u->mail) {
            $subject = "Congratulations! You've earned the $badge->title Badge";
            $from = variable_get('site_mail', ini_get('sendmail_from'));
            if ($badge->email_attachment) {
              summergame_email_attachment($u->mail, $subject, $badge->email_message, $from, $badge->email_attachment);
            }
            else {
              mail($u->mail, $subject, $badge->email_message, "From: $from");
            }
            $messages[] = "NOTE: A special message has been sent to $u->mail with further information";
          }
          else {
            $messages[] = "NOTE: This Badge includes a special email message, but we could not find an email address for you";
          }
        }
      }
    }
  }

  return $messages;
}

/**
 * UTILITY: Award a badge to a player
 */
function summergame_player_award_badge($pid, $bid) {
  $db = \Drupal::database();
  $res = $db->insert('sg_players_badges')->fields([
    'pid' => $pid,
    'bid' => $bid,
    'timestamp' => time(),
  ])->execute();

  return $res->rowCount();
}

/**
 * UTILITY: Update Badges for All Players within a given game term. Use when
 * creating new badges that should be awarded to existing player scores, such as
 * Master badges at the end of the game season.
 */
function summergame_check_all_player_badges($game_term = '') {
  $p_count = 0;
  $res = db_query("SELECT pid FROM sg_ledger WHERE game_term = '%s' GROUP BY pid", $game_term);
  while ($p = db_fetch_object($res)) {
    summergame_player_check_badges($p->pid, $game_term);
    if (++$p_count % 100 == 0) {
      echo date("Y-m-d H:i:s") . "Processed $p_count Players..." . PHP_EOL;
    }
  }
}

/**
 * PAGE: Generate and return a PDF version of the game card PDF
 */
/*
function summergame_pdf($type = 'adult', $code_id = 0) {
  $libphp_path = variable_get('summergame_libphp_path', '');
  require_once($libphp_path . 'contrib/fpdf/fpdf.php');
  require_once($libphp_path . 'contrib/fpdi/fpdi.php');
  require_once($libphp_path . 'contrib/redisent/redisent.php');
  $file_path = drupal_get_path('module', 'summergame') . '/pdf/';
  $redis = new Redisent('multivac');

  if ($type == 'gamecode') {
    $gamecode = db_fetch_object(db_query("SELECT * FROM sg_game_codes WHERE code_id = %d", $code_id));

    $event_code = strtoupper($gamecode->text); // Code for the event, Need to be in all CAPS
    $event_points = $gamecode->points . ' POINTS'; // Points for the event
    $description = $gamecode->description; // Description of Code
    $description = array_reverse(explode("\n", wordwrap($description, 100)));

    $code_link = url('summergame/player/gamecode',
                     array('absolute' => TRUE,
                           'query' => array('text' => $event_code),
                           )
                    );
    $qrcode = 'http://qrickit.com/api/qr?d=' . //'http://api.qrserver.com/v1/create-qr-code/?data=' .
              urlencode($code_link);

    // initiate FPDI
    //$pdf =& new FPDI('L', 'mm', 'Letter');
    $pdf->SetAutoPageBreak(FALSE);
    $pdf->AddPage();

    // set the sourcefile
    $pdf->setSourceFile($file_path . 'code_template.pdf');
    $tplidx = $pdf->importPage(1);
    $pdf->useTemplate($tplidx);
    $pdf->SetMargins(20, 17);
    $page_width = $pdf->w - $pdf->lMargin - $pdf->rMargin;

    // now write some text
    $pdf->AddFont('Quicksand-Bold', '', 'Quicksand-Bold.php');
    $font_size = 100;
    $pdf->SetFont('Quicksand-Bold', '', $font_size);
    while ($pdf->GetStringWidth($event_code) > $page_width) {
      $font_size -= 5;
      $pdf->SetFont('Quicksand-Bold', '', $font_size);
    }
    $pdf->SetXY($pdf->lMargin, 53);
    $pdf->Cell(0, 10, $event_code, 0, 1, 'C');

    $pdf->SetFont('Quicksand-Bold', '', 95);
    $pdf->SetXY($pdf->lMargin, 125);
    $pdf->Cell(0, 10, $event_points, 0, 1, 'C');

/*
    // Description
    $desc_Y = 192;
    $pdf->SetFont('Quicksand-Bold', '', 13);
    foreach ($description as $desc_line) {
      $pdf->SetXY($pdf->lMargin, $desc_Y);
      $pdf->Cell($page_width - 35, 7, $desc_line, 0);
      $desc_Y -= 7;
    }
*/
/*
    // add the QR Code
    $pdf->SetXY(-50, -50);
    $pdf->Image($qrcode, NULL, NULL, 30, 30, 'PNG');

    $pdf->Output($event_code . '_code.pdf', 'D');
  }
  else if ($type == 'youth') {
    $redis->incr('ygpdfcounter');
    drupal_goto($file_path . 'SG_Youth_2017.pdf');
  }
  else { // default to the adult single player form
    $redis->incr('agpdfcounter');
    drupal_goto($file_path . 'SG_Adult_Teen_2017.pdf');
  }
}
*/

/**
 * Page: Merge Two Player Records
 */
/*
function summergame_admin_players_merge($pid1, $pid2, $confirm = '') {
  if ($confirm) {
    summergame_players_merge($pid1, $pid2);
    drupal_set_message("Player #$pid2 merged into Player #$pid1");
    drupal_goto("summergame/player/$pid1");
  }

  $p1 = summergame_player_load(array('pid' => $pid1));
  $p2 = summergame_player_load(array('pid' => $pid2));

  if ($p1['pid'] && $p2['pid']) {
    $p1_points = summergame_get_player_points($pid1);
    $p1['balance'] = $p1_points['balance'];
    $p1['total'] = $p1_points['total'];

    $p2_points = summergame_get_player_points($pid2);
    $p2['balance'] = $p2_points['balance'];
    $p2['total'] = $p2_points['total'];

    $merge_table = array();
    foreach ($p2 as $field => $p2_data) {
      $arrows = (!empty($p2_data) && empty($p1[$field]) ? '<strong>>>></strong>' : '');
      $merge_table[] = array("<strong>$field</strong>", $p2_data, $arrows, $p1[$field]);
    }

    $content .= "<h1>Merge These Player Records?</h1>";
    $content .= '<p style="color: red">Warning: Player record #' . $p2['pid'] . ' will be deleted as a result of this merge</p>';

    $content .= theme('table', array('', 'Player 2', '>>>', 'Player 1'), $merge_table);

    $content .= '<ul>';
    $content .= '<li class="button green">' . l('MERGE', $_GET['q'] . '/1') . '</li>';
    $content .= '<li class="button red">' .l('Cancel', 'summergame/admin') . '</li>';
    $content .= '</ul>';

    return $content;
  }
  else {
    drupal_set_message('Invalid Player IDs', 'error');
    drupal_goto('summergame/admin');
  }
}
*/

/**
 * UTILITY: Merge Two Player Records
 * Additional info from player 2 is added to player 1
 */
function summergame_players_merge($pid1, $pid2) {
  $p1 = summergame_player_load(array('pid' => $pid1));
  $p2 = summergame_player_load(array('pid' => $pid2));

  // Update Player Data Fields
  foreach ($p2 as $field => $data) {
    if (empty($p1[$field])) {
      $p1[$field] = $data;
    }
  }
  summergame_player_save($p1);

  // Check for duplicate Game Codes and remove from old player
  $duplicate_codes = array();
  $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE '%%gamecode:%%'", $pid1);
  while ($row = db_fetch_array($res)) {
    if (preg_match('/gamecode:([\w]+)/', $row['metadata'], $matches)) {
      $duplicate_codes[] = $matches[1];
    }
  }
  if (count($duplicate_codes)) {
    foreach ($duplicate_codes as $duplicate) {
      db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata like '%%gamecode:%s%%'", $pid2, $duplicate);
    }
  }

  // Remove duplicate Signup and Completed bonuses
  $res = db_query("SELECT COUNT(lid) AS count FROM sg_ledger WHERE type = 'Signup' AND (pid = %d OR pid = %d)", $pid1, $pid2);
  $ledger = db_fetch_object($res);
  if ($ledger->count > 1) {
    db_query("DELETE FROM sg_ledger WHERE pid = %d AND type = 'Signup'", $pid2);
  }
  $res = db_query("SELECT COUNT(lid) AS count FROM sg_ledger WHERE type = 'Completed' AND (pid = %d OR pid = %d)", $pid1, $pid2);
  $ledger = db_fetch_object($res);
  if ($ledger->count > 1) {
    db_query("DELETE FROM sg_ledger WHERE pid = %d AND type = 'Completed'", $pid2);
  }

  // Remove duplicate badges and bonuses
  $badges = array();
  $res = db_query("SELECT * FROM sg_badges, sg_players_badges WHERE sg_badges.bid = sg_players_badges.bid AND sg_players_badges.pid = %d", $pid1);
  while ($badge = db_fetch_object($res)) {
    $badges[] = $badge;
  }
  foreach($badges as $badge) {
    db_query("DELETE FROM sg_players_badges WHERE pid = %d and bid = %d", $pid2, $badge->bid);
    $badge_description = "Earned the $badge->title Badge";
    db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata = 'Badge Bonus' AND description = '%s'", $pid2, $badge_description);
  }

  // FRIEND CODE CLEANUP ///////////////////////////////////////////////////////
  // Remove friend codes if new and old entered each other's codes
  db_query("DELETE FROM sg_ledger WHERE pid = %d and metadata LIKE 'fc_player:%d'", $pid1, $pid2);
  db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_follower:%d'", $pid1, $pid2);
  db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_friend:%d'", $pid1, $pid2);
  db_query("DELETE FROM sg_ledger WHERE pid = %d and metadata LIKE 'fc_player:%d'", $pid2, $pid1);
  db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_follower:%d'", $pid2, $pid1);
  db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_friend:%d'", $pid2, $pid1);

  // Remove duplicate Friend Codes from old player
  $duplicate_fcs = array();
  $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_player:%%'", $pid1);
  while ($row = db_fetch_array($res)) {
    if (preg_match('/fc_player:([\d]+)/', $row['metadata'], $matches)) {
      $duplicate_fcs[] = $matches[1];
    }
  }
  if (count($duplicate_fcs)) {
    foreach ($duplicate_fcs as $duplicate) {
      db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_player:%d'", $pid2, $duplicate);
    }
  }

  // Remove duplicate Friend Bonuses from old player
  $duplicate_fbs = array();
  $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_friend:%%'", $pid1);
  while ($row = db_fetch_array($res)) {
    if (preg_match('/fc_friend:([\d]+)/', $row['metadata'], $matches)) {
      $duplicate_fbs[] = $matches[1];
    }
  }
  if (count($duplicate_fbs)) {
    foreach ($duplicate_fbs as $duplicate) {
      db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_friend:%d'", $pid2, $duplicate);
    }
  }

  // Delete old player Friend Codes from any player who also entered new player Friend Code
  $res = db_query("SELECT * FROM sg_ledger WHERE metadata LIKE 'fc_player:%d'", $pid1);
  while ($row = db_fetch_object($res)) {
    db_query("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_player:%d'", $row->pid, $pid2);
  }

  // Delete old player Friend Bonuses from any player who also has Friend Bonus from new player
  $res = db_query("SELECT * FROM sg_ledger WHERE metadata LIKE 'fc_friend:%d'", $pid1);
  while ($row = db_fetch_object($res)) {
    db_queryd("DELETE FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_friend:%d'", $row->pid, $pid2);
  }

  // Update Friend Codes from old player to point to new player
  db_query("UPDATE sg_ledger SET metadata = 'fc_player:%d' WHERE metadata = 'fc_player:%d'", $pid1, $pid2);

  // Award new Friend Bonuses to new player and any player who are now reciprocal friends but do not have bonus
  $following_pids = array();
  $res = db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_player:%%'", $pid1);
  while ($row = db_fetch_array($res)) {
    if (preg_match('/fc_player:([\d]+)/', $row['metadata'], $matches)) {
      $following_pids[] = $matches[1];
    }
  }
  if (count($following_pids)) {
    foreach ($following_pids as $following_pid) {
      // Check if they are a friend
      $row = db_fetch_object(db_query("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_player:%d'", $following_pid, $pid1));
      if ($row->lid) {
        // Friends! Check for bonuses
        $pf_row = db_fetch_object("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_friend:%d'", $pid1, $following_pid);
        if (!$pf_row->lid) {
          // give player friend bonus
          summergame_player_points($pid1, 50, 'Friend Code', 'You and Player #' . $following_pid . ' are now friends!', 'fc_friend:' . $following_pid);
        }
        $of_row = db_fetch_object("SELECT * FROM sg_ledger WHERE pid = %d AND metadata LIKE 'fc_friend:%d'", $following_pid, $pid1);
        if (!$of_row->lid) {
          // give other friend bonus
          summergame_player_points($following_pid, 50, 'Friend Code', 'You and Player #' . $pid1 . ' are now friends!', 'fc_friend:' . $pid1);
        }
      }
    }
  }

  // Update remaing player2 data to point at player1 and delete player 2
  db_query("UPDATE sg_ledger SET pid = %d WHERE pid = %d", $pid1, $pid2);
  db_query("UPDATE sg_players_badges SET pid = %d WHERE pid = %d", $pid1, $pid2);
  db_query("DELETE FROM sg_players WHERE pid = %d", $pid2);
}

function summergame_intervention_form(&$form_state) {
  $form = array(
    'title' => array('#value' => '<h1>Geekly Points Intervention</h1>'),
  );

  $form['to_pid'] = array(
    '#type' => 'textfield',
    '#title' => t('Player ID'),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Player ID of the player to receive points'),
  );
  $form['points'] = array(
    '#type' => 'textfield',
    '#title' => t('Points'),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Number of points to award to the player'),
  );
  $form['game_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Game Term'),
    '#default_value' => variable_get('summergame_current_game_term', ''),
    '#size' => 32,
    '#maxlength' => 32,
    '#description' => t('Game Term where the points will be awarded'),
  );
  $form['description'] = array(
    '#type' => 'textfield',
    '#title' => t('Description'),
    '#size' => 64,
    '#maxlength' => 64,
    '#description' => t('Add a description for this points award (optional)'),
  );
  $form['from_pid'] = array(
    '#type' => 'textfield',
    '#title' => t('From Player ID'),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Player ID of the player giving points in a transfer (optional)'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('POINTS MAKE'),
  );

  return $form;
}

function summergame_intervention_form_submit($form, &$form_state) {
  $to_pid = $form_state['values']['to_pid'];
  $points = $form_state['values']['points'];
  $game_term = $form_state['values']['game_term'];
  $description = $form_state['values']['description'];
  $from_pid = $form_state['values']['from_pid'];

  if ($player = summergame_player_load(array('pid' => $to_pid))) {
    $player_link = l('Player #' . $to_pid, 'summergame/player/' . $to_pid);
    if ($from_pid) {
      if ($from_player = summergame_player_load(array('pid' => $from_pid))) {
        // Tranfer points from from_player to player
        $from_player_link = l('Player #' . $from_pid, 'summergame/player/' . $from_pid);
        summergame_player_points($from_pid, -$points, 'Geekly Intervention',
                                 "Transfer to Player #$to_pid" . ($description ? ', ' . $description : ''),
                                 'delete:no', $game_term);
        summergame_player_points($to_pid, $points, 'Geekly Intervention',
                                 "Transfer from Player #$from_pid" . ($description ? ', ' . $description : ''),
                                 '', $game_term);
        drupal_set_message("Transferred $points $game_term points from $from_player_link to $player_link");
      }
      else {
        drupal_set_message("No player with ID #$from_pid could be found", 'error');
      }
    }
    else {
      // Award points to the player
      summergame_player_points($to_pid, $points, 'Geekly Intervention',
                               "Points awarded" . ($description ? ', ' . $description : ''),
                               '', $game_term);
      drupal_set_message("Awarded $points $game_term points to $player_link");
    }
  }
  else {
    drupal_set_message("No player with ID #$to_pid could be found", 'error');
  }

  drupal_goto('summergame/admin');
}

function summergame_badgeifier_form(&$form_state) {
  $form = array(
    'title' => array('#value' => '<h1>Player Badgeifier</h1>'),
  );

  $form['pid'] = array(
    '#type' => 'textfield',
    '#title' => t('Player ID'),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Player ID of the player to receive the Badge'),
  );
  $form['badge_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Badge ID'),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('ID of the Badge to award to the player'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Badgeify'),
  );

  return $form;
}

function summergame_badgeifier_form_submit($form, &$form_state) {
  $pid = $form_state['values']['pid'];
  $badge_id = $form_state['values']['badge_id'];

  if ($player = summergame_player_load(array('pid' => $pid))) {
    $player_link = l('Player #' . $pid, 'summergame/player/' . $pid);
    // Award badge to the player
    if (summergame_player_award_badge($pid, $badge_id)) {
      drupal_set_message("Awarded Badge #$badge_id to $player_link");
    }
    else {
      drupal_set_message("Badge #$badge_id NOT awarded to $player_link. Already awarded?", 'error');
    }
  }
  else {
    drupal_set_message("No player with ID #$pid could be found", 'error');
  }

  drupal_goto('summergame/admin');
}

/**
 * UTILITY: Move a player to a different player #
 *
 * Sometimes needed to make sure the correct player is the primary player when multiple players
 * are attached to a single website account.
 */
function summergame_move_player_id($old_pid, $new_pid) {
  // Update ledger
  db_query("UPDATE sg_ledger SET pid = %d WHERE pid = %d", $new_pid, $old_pid);
  // Update player table
  db_query("UPDATE sg_players SET pid = %d WHERE pid = %d", $new_pid, $old_pid);
  // Update players badges
  db_query("UPDATE sg_players_badges SET pid = %d WHERE pid = %d", $new_pid, $old_pid);
  // Update players teams
  db_query("UPDATE sg_players_teams SET pid = %d WHERE pid = %d", $new_pid, $old_pid);
}

/**
 * UTILITY: Send an email message with an attachment
 */
function summergame_email_attachment($to, $subject, $message, $from, $fileatt, $replyto = '') {
  // handles mime type for better receiving
  $ext = strrchr($fileatt , '.');
  switch($ext) {
    case '.doc':
      $ftype = 'application/msword';
      break;
    case '.jpg':
      $ftype = 'image/jpeg';
      break;
    case '.gif':
      $ftype = 'image/gif';
      break;
    case '.zip':
      $ftype = 'application/zip';
      break;
    case '.pdf':
      $ftype = 'application/pdf';
      break;
    case '.swf':
      $ftype = 'application/x-shockwave-flash';
      break;
    case '.mp3':
      $ftype = 'audio/mpeg';
      break;
    case '.mp4':
      $ftype = 'video/mp4v-es';
      break;
    case '.mov':
      $ftype = 'video/quicktime';
      break;
    default:
      $ftype = 'application/octet-stream';
  }

  // read file into $data var
  $file = fopen($fileatt, 'rb');
  $data = fread($file, filesize($fileatt));
  fclose($file);

  // split the file into chunks for attaching
  $content = chunk_split(base64_encode($data));
  $uid = md5(uniqid(time()));

  // build the headers for attachment and html
  $EOL = PHP_EOL;
  $headers = "From: $from$EOL";
  if ($replyto) {
    $headers .= "Reply-To: $replyto$EOL";
  }
  $headers .= "MIME-Version: 1.0$EOL";
  $headers .= "Content-Type: multipart/mixed; boundary=\"$uid\"$EOL$EOL";
  $headers .= "This is a multi-part message in MIME format.$EOL";
  $headers .= "--$uid$EOL";
  $headers .= "Content-type:text/html; charset=iso-8859-1$EOL";
  $headers .= "Content-Transfer-Encoding: 7bit$EOL$EOL";
  $headers .= str_replace($EOL, '<br />', $message) . "$EOL$EOL";
  $headers .= "--$uid$EOL";
  $headers .= "Content-Type: $ftype; name=\"" . basename($fileatt) . "\"$EOL";
  $headers .= "Content-Transfer-Encoding: base64$EOL";
  $headers .= "Content-Disposition: attachment; filename=\"" . basename($fileatt) . "\"$EOL$EOL";
  $headers .= "$content$EOL$EOL";
  $headers .= "--$uid--";

  // send mail
  return mail($to, $subject, $message, $headers);
}
